import { AdyenIcon } from '@/components/icons'
import { createOperationDropdown, defineBlock } from '../helpers'

export const AdyenBlock = defineBlock({
  type: 'adyen',
  name: 'Adyen',
  description: 'Global payment platform for businesses of all sizes.',
  longDescription:
    'Integrate with Adyen to process payments, manage transactions, and handle payouts globally. Adyen is an end-to-end payments platform that powers businesses like Uber, Spotify, and Microsoft with unified commerce across online, mobile, and in-store channels. Perfect for accepting payments, managing refunds, and accessing real-time financial data.',
  category: 'tools',
  bgColor: '#0ABF53',
  icon: AdyenIcon,
  subBlocks: [
    {
      id: 'credential',
      title: 'Adyen API Key',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter your Adyen API key',
      password: true,
    },
    {
      id: 'merchantAccount',
      title: 'Merchant Account',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Your merchant account name',
    },
    {
      id: 'environment',
      title: 'Environment',
      type: 'dropdown',
      layout: 'full',
      options: [
        { id: 'test', label: 'Test' },
        { id: 'live', label: 'Live' },
      ],
      value: () => 'test',
    },
    createOperationDropdown({
      operations: [
        { id: 'create_payment', label: 'Create Payment' },
        { id: 'get_payment', label: 'Get Payment' },
        { id: 'capture_payment', label: 'Capture Payment' },
        { id: 'refund_payment', label: 'Refund Payment' },
        { id: 'cancel_payment', label: 'Cancel Payment' },
        { id: 'create_payout', label: 'Create Payout' },
        { id: 'get_balance', label: 'Get Balance' },
        { id: 'list_transactions', label: 'List Transactions' },
      ],
      defaultValue: 'create_payment',
    }),
    {
      id: 'paymentReference',
      title: 'Payment Reference',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter payment reference/PSP reference',
      condition: {
        field: 'operation',
        value: ['get_payment', 'capture_payment', 'refund_payment', 'cancel_payment'],
      },
    },
    {
      id: 'amount',
      title: 'Amount (in minor units, e.g., cents)',
      type: 'short-input',
      layout: 'half',
      placeholder: '1000',
      condition: {
        field: 'operation',
        value: ['create_payment', 'refund_payment', 'create_payout'],
      },
    },
    {
      id: 'currency',
      title: 'Currency',
      type: 'short-input',
      layout: 'half',
      placeholder: 'USD, EUR, GBP',
      condition: {
        field: 'operation',
        value: ['create_payment', 'refund_payment', 'create_payout'],
      },
    },
    {
      id: 'reference',
      title: 'Reference',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Your order reference',
      condition: { field: 'operation', value: ['create_payment', 'create_payout'] },
    },
    {
      id: 'shopperEmail',
      title: 'Shopper Email',
      type: 'short-input',
      layout: 'half',
      placeholder: 'customer@example.com',
      condition: { field: 'operation', value: 'create_payment' },
    },
    {
      id: 'shopperReference',
      title: 'Shopper Reference',
      type: 'short-input',
      layout: 'half',
      placeholder: 'Unique shopper ID',
      condition: { field: 'operation', value: 'create_payment' },
    },
    {
      id: 'paymentMethod',
      title: 'Payment Method (JSON)',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder:
        '{"type": "scheme", "encryptedCardNumber": "...", "encryptedExpiryMonth": "...", "encryptedExpiryYear": "...", "encryptedSecurityCode": "..."}',
      condition: { field: 'operation', value: 'create_payment' },
    },
    {
      id: 'returnUrl',
      title: 'Return URL',
      type: 'short-input',
      layout: 'full',
      placeholder: 'https://your-website.com/payment/return',
      condition: { field: 'operation', value: 'create_payment' },
    },
    {
      id: 'countryCode',
      title: 'Country Code',
      type: 'short-input',
      layout: 'half',
      placeholder: 'US, GB, NL',
      condition: { field: 'operation', value: 'create_payment' },
    },
    {
      id: 'shopperLocale',
      title: 'Shopper Locale',
      type: 'short-input',
      layout: 'half',
      placeholder: 'en-US',
      condition: { field: 'operation', value: 'create_payment' },
    },
    {
      id: 'bankAccount',
      title: 'Bank Account (JSON)',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: '{"ownerName": "John Doe", "iban": "NL13TEST0123456789"}',
      condition: { field: 'operation', value: 'create_payout' },
    },
    {
      id: 'billingAddress',
      title: 'Billing Address (JSON)',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder:
        '{"street": "123 Main St", "city": "New York", "postalCode": "10001", "country": "US"}',
      condition: { field: 'operation', value: 'create_payment' },
    },
  ],
  tools: {
    access: ['adyen_api'],
    config: {
      tool: () => 'adyen_api',
    },
  },
  inputs: {
    credential: { type: 'string', required: true },
    merchantAccount: { type: 'string', required: true },
    environment: { type: 'string', required: true },
    operation: { type: 'string', required: true },
    paymentReference: { type: 'string', required: false },
    amount: { type: 'number', required: false },
    currency: { type: 'string', required: false },
    reference: { type: 'string', required: false },
    shopperEmail: { type: 'string', required: false },
    shopperReference: { type: 'string', required: false },
    paymentMethod: { type: 'json', required: false },
    returnUrl: { type: 'string', required: false },
    countryCode: { type: 'string', required: false },
    shopperLocale: { type: 'string', required: false },
    bankAccount: { type: 'json', required: false },
    billingAddress: { type: 'json', required: false },
  },
  outputs: {
    response: {
      type: {
        data: 'json',
      },
    },
  },
})
