import { BambooHRIcon } from '@/components/icons'
import { createOAuthSubBlock, createOperationDropdown, defineBlock } from '../helpers'

export const BambooHRBlock = defineBlock({
  type: 'bamboohr',
  name: 'BambooHR',
  description: 'HR software for small and medium-sized businesses.',
  longDescription:
    'Integrate with BambooHR to manage employee records, time-off tracking, performance management, and HR reporting. BambooHR is an all-in-one HR platform that helps growing companies centralize employee data, automate HR workflows, and build great company culture. Perfect for managing employee information, onboarding, and time-off requests.',
  category: 'tools',
  bgColor: '#73C41D',
  icon: BambooHRIcon,
  subBlocks: [
    createOAuthSubBlock({
      provider: 'bamboohr',
      serviceId: 'bamboohr',
      requiredScopes: [],
      title: 'BambooHR Account',
      placeholder: 'Select BambooHR account',
    }),
    {
      id: 'subdomain',
      title: 'Subdomain',
      type: 'short-input',
      layout: 'full',
      placeholder: 'your-company (from your-company.bamboohr.com)',
    },
    createOperationDropdown({
      operations: [
        { id: 'list_employees', label: 'List Employees' },
        { id: 'get_employee', label: 'Get Employee' },
        { id: 'update_employee', label: 'Update Employee' },
        { id: 'list_time_off_requests', label: 'List Time Off Requests' },
        { id: 'get_time_off_request', label: 'Get Time Off Request' },
        { id: 'create_time_off_request', label: 'Create Time Off Request' },
        { id: 'list_time_off_types', label: 'List Time Off Types' },
        { id: 'get_employee_directory', label: 'Get Employee Directory' },
        { id: 'list_custom_reports', label: 'List Custom Reports' },
        { id: 'get_custom_report', label: 'Get Custom Report' },
      ],
      defaultValue: 'list_employees',
    }),
    {
      id: 'employeeId',
      title: 'Employee ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter employee ID',
      condition: {
        field: 'operation',
        value: ['get_employee', 'update_employee', 'create_time_off_request'],
      },
    },
    {
      id: 'requestId',
      title: 'Time Off Request ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter request ID',
      condition: { field: 'operation', value: 'get_time_off_request' },
    },
    {
      id: 'reportId',
      title: 'Report ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter custom report ID',
      condition: { field: 'operation', value: 'get_custom_report' },
    },
    {
      id: 'firstName',
      title: 'First Name',
      type: 'short-input',
      layout: 'half',
      placeholder: 'John',
      condition: { field: 'operation', value: 'update_employee' },
    },
    {
      id: 'lastName',
      title: 'Last Name',
      type: 'short-input',
      layout: 'half',
      placeholder: 'Doe',
      condition: { field: 'operation', value: 'update_employee' },
    },
    {
      id: 'jobTitle',
      title: 'Job Title',
      type: 'short-input',
      layout: 'half',
      placeholder: 'Software Engineer',
      condition: { field: 'operation', value: 'update_employee' },
    },
    {
      id: 'department',
      title: 'Department',
      type: 'short-input',
      layout: 'half',
      placeholder: 'Engineering',
      condition: { field: 'operation', value: 'update_employee' },
    },
    {
      id: 'timeOffTypeId',
      title: 'Time Off Type ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter time off type ID',
      condition: { field: 'operation', value: 'create_time_off_request' },
    },
    {
      id: 'startDate',
      title: 'Start Date',
      type: 'short-input',
      layout: 'half',
      placeholder: '2025-06-01',
      condition: { field: 'operation', value: 'create_time_off_request' },
    },
    {
      id: 'endDate',
      title: 'End Date',
      type: 'short-input',
      layout: 'half',
      placeholder: '2025-06-05',
      condition: { field: 'operation', value: 'create_time_off_request' },
    },
    {
      id: 'amount',
      title: 'Amount (hours/days)',
      type: 'short-input',
      layout: 'half',
      placeholder: '8',
      condition: { field: 'operation', value: 'create_time_off_request' },
    },
    {
      id: 'notes',
      title: 'Notes',
      type: 'long-input',
      layout: 'full',
      placeholder: 'Reason for time off request',
      condition: { field: 'operation', value: 'create_time_off_request' },
    },
    {
      id: 'fields',
      title: 'Fields to Retrieve (comma separated)',
      type: 'short-input',
      layout: 'full',
      placeholder: 'firstName,lastName,jobTitle,department,hireDate',
      condition: { field: 'operation', value: ['list_employees', 'get_employee'] },
    },
  ],
  tools: {
    access: ['bamboohr_api'],
    config: {
      tool: () => 'bamboohr_api',
    },
  },
  inputs: {
    credential: { type: 'string', required: true },
    subdomain: { type: 'string', required: true },
    operation: { type: 'string', required: true },
    employeeId: { type: 'string', required: false },
    requestId: { type: 'string', required: false },
    reportId: { type: 'string', required: false },
    firstName: { type: 'string', required: false },
    lastName: { type: 'string', required: false },
    jobTitle: { type: 'string', required: false },
    department: { type: 'string', required: false },
    timeOffTypeId: { type: 'string', required: false },
    startDate: { type: 'string', required: false },
    endDate: { type: 'string', required: false },
    amount: { type: 'string', required: false },
    notes: { type: 'string', required: false },
    fields: { type: 'string', required: false },
  },
  outputs: {
    response: {
      type: {
        data: 'json',
      },
    },
  },
})
