import { BasecampIcon } from '@/components/icons'
import {
  createOAuthSubBlock,
  createOperationDropdown,
  createSimpleToolConfig,
  defineBlock,
} from '../helpers'

export const BasecampBlock = defineBlock({
  type: 'basecamp',
  name: 'Basecamp',
  description: 'Project management and team communication',
  longDescription:
    'Integrate with Basecamp to manage projects, create to-dos, post messages, share files, and collaborate with team members and clients. Perfect for small teams prioritizing communication using OAuth 2.0 authentication.',
  category: 'tools',
  bgColor: '#1D2D35',
  icon: BasecampIcon,
  subBlocks: [
    createOAuthSubBlock({
      provider: 'basecamp',
      serviceId: 'basecamp',
      requiredScopes: [],
      title: 'Basecamp Account',
      placeholder: 'Select Basecamp account',
    }),
    createOperationDropdown({
      operations: [
        { id: 'list_projects', label: 'List Projects' },
        { id: 'get_project', label: 'Get Project' },
        { id: 'create_project', label: 'Create Project' },
        { id: 'list_todos', label: 'List To-dos' },
        { id: 'create_todo', label: 'Create To-do' },
        { id: 'update_todo', label: 'Update To-do' },
        { id: 'complete_todo', label: 'Complete To-do' },
        { id: 'create_message', label: 'Create Message' },
        { id: 'list_messages', label: 'List Messages' },
        { id: 'upload_file', label: 'Upload File' },
        { id: 'list_people', label: 'List People' },
      ],
      defaultValue: 'list_projects',
    }),
    {
      id: 'projectId',
      title: 'Project ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter project ID',
      condition: {
        field: 'operation',
        value: [
          'get_project',
          'list_todos',
          'create_todo',
          'create_message',
          'list_messages',
          'upload_file',
        ],
      },
    },
    {
      id: 'projectName',
      title: 'Project Name',
      type: 'short-input',
      layout: 'full',
      placeholder: 'My New Project',
      condition: { field: 'operation', value: 'create_project' },
    },
    {
      id: 'projectDescription',
      title: 'Project Description',
      type: 'long-input',
      layout: 'full',
      placeholder: 'Project description',
      condition: { field: 'operation', value: 'create_project' },
    },
    {
      id: 'todoId',
      title: 'To-do ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter to-do ID',
      condition: { field: 'operation', value: ['update_todo', 'complete_todo'] },
    },
    {
      id: 'todoContent',
      title: 'To-do Content',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Task description',
      condition: { field: 'operation', value: ['create_todo', 'update_todo'] },
    },
    {
      id: 'messageSubject',
      title: 'Message Subject',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Message title',
      condition: { field: 'operation', value: 'create_message' },
    },
    {
      id: 'messageContent',
      title: 'Message Content',
      type: 'long-input',
      layout: 'full',
      placeholder: 'Message body',
      condition: { field: 'operation', value: 'create_message' },
    },
    {
      id: 'dueDate',
      title: 'Due Date',
      type: 'short-input',
      layout: 'half',
      placeholder: 'YYYY-MM-DD',
      condition: { field: 'operation', value: 'create_todo' },
    },
  ],
  tools: {
    access: ['basecamp_api'],
    config: createSimpleToolConfig('basecamp_api'),
  },
  inputs: {
    credential: { type: 'string', required: true },
    operation: { type: 'string', required: true },
    projectId: { type: 'string', required: false },
    projectName: { type: 'string', required: false },
    projectDescription: { type: 'string', required: false },
    todoId: { type: 'string', required: false },
    todoContent: { type: 'string', required: false },
    messageSubject: { type: 'string', required: false },
    messageContent: { type: 'string', required: false },
    dueDate: { type: 'string', required: false },
  },
  outputs: {
    response: {
      type: {
        data: 'json',
      },
    },
  },
})
