import { ByBitIcon } from '@/components/icons'
import { createOperationDropdown, defineBlock } from '../helpers'

export const ByBitBlock = defineBlock({
  type: 'bybit',
  name: 'ByBit',
  description: '⚠️ Derivatives trading, spot market, and futures',
  longDescription:
    'Connect to ByBit API for cryptocurrency derivatives trading, spot trading, and futures contracts. Access market data, execute trades, manage positions, and track order history. Supports perpetual contracts, inverse futures, and spot trading. Uses API key authentication. ⚠️ REGULATORY NOTICE: This integration is for authorized use only. Derivatives and futures trading carries extremely high financial risk and may result in total loss. Users must comply with all applicable regulations. Not available in restricted jurisdictions.',
  category: 'tools',
  bgColor: '#F7A600',
  icon: ByBitIcon,
  subBlocks: [
    {
      id: 'apiKey',
      title: 'API Key',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Your ByBit API Key',
      password: true,
      description: '⚠️ Keep your API keys secure. Use testnet for testing.',
    },
    {
      id: 'apiSecret',
      title: 'API Secret',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Your ByBit API Secret',
      password: true,
    },
    {
      id: 'testnet',
      title: 'Use Testnet',
      type: 'switch',
      layout: 'half',
      description: 'Enable for testing with fake funds',
    },
    createOperationDropdown({
      operations: [
        { id: 'get_server_time', label: 'Get Server Time' },
        { id: 'get_kline', label: 'Get Kline/Candlestick' },
        { id: 'get_ticker', label: 'Get Latest Ticker' },
        { id: 'get_orderbook', label: 'Get Order Book' },
        { id: 'get_recent_trades', label: 'Get Recent Trades' },
        { id: 'get_wallet_balance', label: 'Get Wallet Balance' },
        { id: 'get_positions', label: 'Get Positions' },
        { id: 'get_active_orders', label: 'Get Active Orders' },
        { id: 'get_order_history', label: 'Get Order History' },
        { id: 'place_order', label: '⚠️ Place Order' },
        { id: 'cancel_order', label: 'Cancel Order' },
        { id: 'cancel_all_orders', label: 'Cancel All Orders' },
        { id: 'set_leverage', label: '⚠️ Set Leverage' },
        { id: 'get_funding_rate', label: 'Get Funding Rate' },
        { id: 'get_risk_limit', label: 'Get Risk Limit' },
      ],
      defaultValue: 'get_ticker',
    }),
    {
      id: 'category',
      title: 'Product Category',
      type: 'dropdown',
      layout: 'half',
      options: [
        { id: 'spot', label: 'Spot' },
        { id: 'linear', label: 'USDT Perpetual' },
        { id: 'inverse', label: 'Inverse Perpetual' },
        { id: 'option', label: 'Options' },
      ],
      condition: {
        field: 'operation',
        value: [
          'get_ticker',
          'get_orderbook',
          'get_kline',
          'get_recent_trades',
          'get_wallet_balance',
          'get_positions',
          'get_active_orders',
          'place_order',
          'cancel_order',
          'set_leverage',
        ],
      },
    },
    {
      id: 'symbol',
      title: 'Symbol',
      type: 'short-input',
      layout: 'half',
      placeholder: 'BTCUSDT, ETHUSDT',
      condition: {
        field: 'operation',
        value: [
          'get_ticker',
          'get_orderbook',
          'get_kline',
          'get_recent_trades',
          'get_positions',
          'get_active_orders',
          'place_order',
          'set_leverage',
          'get_funding_rate',
        ],
      },
    },
    {
      id: 'interval',
      title: 'Kline Interval',
      type: 'dropdown',
      layout: 'half',
      options: [
        { id: '1', label: '1 Minute' },
        { id: '5', label: '5 Minutes' },
        { id: '15', label: '15 Minutes' },
        { id: '60', label: '1 Hour' },
        { id: '240', label: '4 Hours' },
        { id: 'D', label: '1 Day' },
        { id: 'W', label: '1 Week' },
      ],
      condition: { field: 'operation', value: 'get_kline' },
    },
    {
      id: 'limit',
      title: 'Limit',
      type: 'short-input',
      layout: 'half',
      placeholder: '200',
      condition: {
        field: 'operation',
        value: ['get_kline', 'get_orderbook', 'get_recent_trades', 'get_order_history'],
      },
    },
    // Order fields
    {
      id: 'side',
      title: 'Order Side',
      type: 'dropdown',
      layout: 'half',
      options: [
        { id: 'Buy', label: '🟢 Buy' },
        { id: 'Sell', label: '🔴 Sell' },
      ],
      condition: { field: 'operation', value: 'place_order' },
    },
    {
      id: 'orderType',
      title: 'Order Type',
      type: 'dropdown',
      layout: 'half',
      options: [
        { id: 'Market', label: 'Market' },
        { id: 'Limit', label: 'Limit' },
      ],
      condition: { field: 'operation', value: 'place_order' },
    },
    {
      id: 'qty',
      title: 'Quantity',
      type: 'short-input',
      layout: 'half',
      placeholder: '0.01',
      condition: { field: 'operation', value: 'place_order' },
    },
    {
      id: 'price',
      title: 'Price (for limit orders)',
      type: 'short-input',
      layout: 'half',
      placeholder: '50000',
      condition: { field: 'operation', value: 'place_order' },
    },
    {
      id: 'timeInForce',
      title: 'Time In Force',
      type: 'dropdown',
      layout: 'half',
      options: [
        { id: 'GTC', label: 'Good Till Cancel' },
        { id: 'IOC', label: 'Immediate or Cancel' },
        { id: 'FOK', label: 'Fill or Kill' },
      ],
      condition: { field: 'operation', value: 'place_order' },
    },
    {
      id: 'orderId',
      title: 'Order ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Order ID to cancel',
      condition: { field: 'operation', value: 'cancel_order' },
    },
    {
      id: 'leverage',
      title: 'Leverage',
      type: 'short-input',
      layout: 'half',
      placeholder: '10 (1-100)',
      condition: { field: 'operation', value: 'set_leverage' },
    },
  ],
  tools: {
    access: ['bybit_api'],
    config: {
      tool: () => 'bybit_api',
      params: (params) => {
        const { apiKey, apiSecret, testnet, ...rest } = params as Record<string, any>
        return {
          apiKey,
          apiSecret,
          testnet,
          ...rest,
        }
      },
    },
  },
  inputs: {
    apiKey: { type: 'string', required: true },
    apiSecret: { type: 'string', required: true },
    testnet: { type: 'boolean', required: false },
    operation: { type: 'string', required: true },
    category: { type: 'string', required: false },
    symbol: { type: 'string', required: false },
    interval: { type: 'string', required: false },
    limit: { type: 'number', required: false },
    side: { type: 'string', required: false },
    orderType: { type: 'string', required: false },
    qty: { type: 'string', required: false },
    price: { type: 'string', required: false },
    timeInForce: { type: 'string', required: false },
    orderId: { type: 'string', required: false },
    leverage: { type: 'string', required: false },
  },
  outputs: {
    response: {
      type: {
        success: 'boolean',
        data: 'any',
      },
    },
  },
  compliance: {
    enabled: true,
    tags: [
      'crypto_trading',
      'financial_trading',
      'high_risk',
      'regulated',
      'kyc_required',
      'region_restricted',
    ],
    disclaimer:
      'EXTREME RISK WARNING: Derivatives and futures trading carries exceptionally high financial risk and may result in total loss exceeding initial capital due to leverage. This block is intended for experienced traders only. Users must comply with all applicable financial regulations, KYC/AML requirements, and derivatives trading laws. ByBit services are restricted in numerous jurisdictions. Margin trading and leveraged products are extremely risky and may not be suitable for all investors. Users are solely responsible for ensuring compliance with local laws and regulations.',
    restrictedRegions: [
      'US',
      'UK',
      'China',
      'Singapore',
      'Ontario (Canada)',
      'Many other jurisdictions',
    ],
    requiresLicense: true,
    riskLevel: 'extreme',
  },
})
