import { CloseIcon } from '@/components/icons'
import { createOAuthSubBlock, createOperationDropdown, defineBlock } from '../helpers'

export const CloseBlock = defineBlock({
  type: 'close',
  name: 'Close',
  description: 'Sales CRM built for startups and SMBs to close more deals.',
  longDescription:
    'Integrate with Close CRM to manage leads, contacts, opportunities, and sales activities. Close is a powerful sales CRM designed for inside sales teams with built-in calling, email automation, and advanced reporting. Perfect for high-velocity sales teams that need a CRM that works as hard as they do.',
  category: 'tools',
  bgColor: '#4A5568',
  icon: CloseIcon,
  subBlocks: [
    createOAuthSubBlock({
      provider: 'close',
      serviceId: 'close',
      requiredScopes: [],
      title: 'Close Account',
      placeholder: 'Select Close account',
    }),
    createOperationDropdown({
      operations: [
        { id: 'list_leads', label: 'List Leads' },
        { id: 'get_lead', label: 'Get Lead' },
        { id: 'create_lead', label: 'Create Lead' },
        { id: 'update_lead', label: 'Update Lead' },
        { id: 'list_contacts', label: 'List Contacts' },
        { id: 'create_contact', label: 'Create Contact' },
        { id: 'list_opportunities', label: 'List Opportunities' },
        { id: 'create_opportunity', label: 'Create Opportunity' },
        { id: 'list_tasks', label: 'List Tasks' },
        { id: 'create_task', label: 'Create Task' },
        { id: 'send_email', label: 'Send Email' },
        { id: 'log_call', label: 'Log Call' },
      ],
      defaultValue: 'list_leads',
    }),
    {
      id: 'leadId',
      title: 'Lead ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter lead ID',
      condition: {
        field: 'operation',
        value: ['get_lead', 'update_lead', 'create_contact', 'create_opportunity'],
      },
    },
    {
      id: 'leadName',
      title: 'Lead Name',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Acme Corporation',
      condition: { field: 'operation', value: ['create_lead', 'update_lead'] },
    },
    {
      id: 'contactName',
      title: 'Contact Name',
      type: 'short-input',
      layout: 'full',
      placeholder: 'John Doe',
      condition: { field: 'operation', value: 'create_contact' },
    },
    {
      id: 'email',
      title: 'Email',
      type: 'short-input',
      layout: 'half',
      placeholder: 'john@example.com',
      condition: { field: 'operation', value: ['create_contact', 'send_email'] },
    },
    {
      id: 'phone',
      title: 'Phone',
      type: 'short-input',
      layout: 'half',
      placeholder: '+1234567890',
      condition: { field: 'operation', value: 'create_contact' },
    },
    {
      id: 'opportunityValue',
      title: 'Opportunity Value',
      type: 'short-input',
      layout: 'half',
      placeholder: '50000',
      condition: { field: 'operation', value: 'create_opportunity' },
    },
    {
      id: 'opportunityStatus',
      title: 'Opportunity Status',
      type: 'short-input',
      layout: 'half',
      placeholder: 'active',
      condition: { field: 'operation', value: 'create_opportunity' },
    },
    {
      id: 'taskText',
      title: 'Task Description',
      type: 'long-input',
      layout: 'full',
      placeholder: 'Follow up with prospect about demo',
      condition: { field: 'operation', value: 'create_task' },
    },
    {
      id: 'dueDate',
      title: 'Due Date',
      type: 'short-input',
      layout: 'half',
      placeholder: '2025-12-31',
      condition: { field: 'operation', value: 'create_task' },
    },
    {
      id: 'emailSubject',
      title: 'Email Subject',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Following up on our conversation',
      condition: { field: 'operation', value: 'send_email' },
    },
    {
      id: 'emailBody',
      title: 'Email Body',
      type: 'long-input',
      layout: 'full',
      placeholder: 'Hi, I wanted to follow up...',
      condition: { field: 'operation', value: 'send_email' },
    },
    {
      id: 'callDuration',
      title: 'Call Duration (seconds)',
      type: 'short-input',
      layout: 'half',
      placeholder: '300',
      condition: { field: 'operation', value: 'log_call' },
    },
    {
      id: 'callNote',
      title: 'Call Note',
      type: 'long-input',
      layout: 'full',
      placeholder: 'Discussed pricing and next steps',
      condition: { field: 'operation', value: 'log_call' },
    },
    {
      id: 'customFields',
      title: 'Custom Fields (JSON)',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: '{"custom_field_1": "value1"}',
      condition: {
        field: 'operation',
        value: ['create_lead', 'update_lead', 'create_contact', 'create_opportunity'],
      },
    },
  ],
  tools: {
    access: ['close_api'],
    config: {
      tool: () => 'close_api',
    },
  },
  inputs: {
    credential: { type: 'string', required: true },
    operation: { type: 'string', required: true },
    leadId: { type: 'string', required: false },
    leadName: { type: 'string', required: false },
    contactName: { type: 'string', required: false },
    email: { type: 'string', required: false },
    phone: { type: 'string', required: false },
    opportunityValue: { type: 'number', required: false },
    opportunityStatus: { type: 'string', required: false },
    taskText: { type: 'string', required: false },
    dueDate: { type: 'string', required: false },
    emailSubject: { type: 'string', required: false },
    emailBody: { type: 'string', required: false },
    callDuration: { type: 'number', required: false },
    callNote: { type: 'string', required: false },
    customFields: { type: 'json', required: false },
  },
  outputs: {
    response: {
      type: {
        data: 'json',
      },
    },
  },
})
