import { CopperIcon } from '@/components/icons'
import { createOAuthSubBlock, createOperationDropdown, defineBlock } from '../helpers'

export const CopperBlock = defineBlock({
  type: 'copper',
  name: 'Copper',
  description: 'Google Workspace native CRM for managing relationships and sales.',
  longDescription:
    'Integrate with Copper CRM to manage your sales pipeline directly from Gmail and Google Workspace. Copper provides seamless contact management, deal tracking, and task automation with deep Google integration. Perfect for teams already using Google Workspace who want native CRM functionality with OAuth 2.0 authentication.',
  category: 'tools',
  bgColor: '#F36E4F',
  icon: CopperIcon,
  subBlocks: [
    createOAuthSubBlock({
      provider: 'copper',
      serviceId: 'copper',
      requiredScopes: [],
      title: 'Copper Account',
      placeholder: 'Select Copper account',
    }),
    createOperationDropdown({
      operations: [
        { id: 'list_people', label: 'List People' },
        { id: 'get_person', label: 'Get Person' },
        { id: 'create_person', label: 'Create Person' },
        { id: 'update_person', label: 'Update Person' },
        { id: 'list_companies', label: 'List Companies' },
        { id: 'create_company', label: 'Create Company' },
        { id: 'list_opportunities', label: 'List Opportunities' },
        { id: 'create_opportunity', label: 'Create Opportunity' },
        { id: 'get_opportunity', label: 'Get Opportunity' },
        { id: 'update_opportunity', label: 'Update Opportunity' },
      ],
      defaultValue: 'list_people',
    }),
    {
      id: 'personId',
      title: 'Person ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter person ID',
      condition: { field: 'operation', value: ['get_person', 'update_person'] },
    },
    {
      id: 'opportunityId',
      title: 'Opportunity ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter opportunity ID',
      condition: { field: 'operation', value: ['get_opportunity', 'update_opportunity'] },
    },
    {
      id: 'name',
      title: 'Name',
      type: 'short-input',
      layout: 'full',
      placeholder: 'John Doe',
      condition: { field: 'operation', value: ['create_person', 'update_person'] },
    },
    {
      id: 'email',
      title: 'Email',
      type: 'short-input',
      layout: 'half',
      placeholder: 'john@example.com',
      condition: { field: 'operation', value: ['create_person', 'update_person'] },
    },
    {
      id: 'phone',
      title: 'Phone',
      type: 'short-input',
      layout: 'half',
      placeholder: '+1234567890',
      condition: { field: 'operation', value: ['create_person', 'update_person'] },
    },
    {
      id: 'companyName',
      title: 'Company Name',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Acme Corporation',
      condition: { field: 'operation', value: 'create_company' },
    },
    {
      id: 'opportunityName',
      title: 'Opportunity Name',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Q1 Enterprise Deal',
      condition: { field: 'operation', value: ['create_opportunity', 'update_opportunity'] },
    },
    {
      id: 'monetaryValue',
      title: 'Monetary Value',
      type: 'short-input',
      layout: 'half',
      placeholder: '50000',
      condition: { field: 'operation', value: ['create_opportunity', 'update_opportunity'] },
    },
    {
      id: 'pipelineStageId',
      title: 'Pipeline Stage ID',
      type: 'short-input',
      layout: 'half',
      placeholder: 'Enter stage ID',
      condition: { field: 'operation', value: ['create_opportunity', 'update_opportunity'] },
    },
    {
      id: 'customFields',
      title: 'Custom Fields (JSON)',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: '{"custom_field_1": "value1"}',
      condition: {
        field: 'operation',
        value: ['create_person', 'update_person', 'create_opportunity', 'update_opportunity'],
      },
    },
  ],
  tools: {
    access: ['copper_api'],
    config: {
      tool: () => 'copper_api',
    },
  },
  inputs: {
    credential: { type: 'string', required: true },
    operation: { type: 'string', required: true },
    personId: { type: 'string', required: false },
    opportunityId: { type: 'string', required: false },
    name: { type: 'string', required: false },
    email: { type: 'string', required: false },
    phone: { type: 'string', required: false },
    companyName: { type: 'string', required: false },
    opportunityName: { type: 'string', required: false },
    monetaryValue: { type: 'number', required: false },
    pipelineStageId: { type: 'string', required: false },
    customFields: { type: 'json', required: false },
  },
  outputs: {
    response: {
      type: {
        data: 'json',
      },
    },
  },
})
