import { FreshBooksIcon } from '@/components/icons'
import {
  createOAuthSubBlock,
  createOperationDropdown,
  createParamTransformer,
  defineBlock,
} from '../helpers'

export const FreshBooksBlock = defineBlock({
  type: 'freshbooks',
  name: 'FreshBooks',
  description: 'Manage invoicing, time tracking, and expenses',
  longDescription:
    'Integrate with FreshBooks to create and manage invoices, track time, manage expenses, handle client billing, and access financial reports. Perfect for freelancers and small service providers with OAuth 2.0 authentication.',
  category: 'tools',
  bgColor: '#0075DD',
  icon: FreshBooksIcon,
  subBlocks: [
    createOAuthSubBlock({
      provider: 'freshbooks',
      serviceId: 'freshbooks',
      requiredScopes: [
        'user:profile:read',
        'user:clients:read',
        'user:clients:write',
        'user:time_entries:read',
        'user:time_entries:write',
        'user:expenses:read',
        'user:expenses:write',
        'user:invoices:read',
        'user:invoices:write',
      ],
      title: 'FreshBooks Account',
      placeholder: 'Select FreshBooks account',
    }),
    createOperationDropdown({
      operations: [
        { id: 'create_invoice', label: 'Create Invoice' },
        { id: 'get_invoice', label: 'Get Invoice' },
        { id: 'list_invoices', label: 'List Invoices' },
        { id: 'update_invoice', label: 'Update Invoice' },
        { id: 'create_client', label: 'Create Client' },
        { id: 'get_client', label: 'Get Client' },
        { id: 'list_clients', label: 'List Clients' },
        { id: 'create_expense', label: 'Create Expense' },
        { id: 'list_expenses', label: 'List Expenses' },
        { id: 'create_time_entry', label: 'Create Time Entry' },
        { id: 'list_time_entries', label: 'List Time Entries' },
        { id: 'get_account_info', label: 'Get Account Info' },
      ],
      defaultValue: 'list_invoices',
    }),
    {
      id: 'invoiceId',
      title: 'Invoice ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter invoice ID',
      condition: { field: 'operation', value: ['get_invoice', 'update_invoice'] },
    },
    {
      id: 'clientId',
      title: 'Client ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter client ID',
      condition: { field: 'operation', value: ['get_client', 'create_invoice'] },
    },
    {
      id: 'clientName',
      title: 'Client Name',
      type: 'short-input',
      layout: 'full',
      placeholder: 'John Doe',
      condition: { field: 'operation', value: 'create_client' },
    },
    {
      id: 'email',
      title: 'Email',
      type: 'short-input',
      layout: 'half',
      placeholder: 'client@example.com',
      condition: { field: 'operation', value: 'create_client' },
    },
    {
      id: 'amount',
      title: 'Amount',
      type: 'short-input',
      layout: 'half',
      placeholder: '100.00',
      condition: { field: 'operation', value: ['create_invoice', 'create_expense'] },
    },
    {
      id: 'description',
      title: 'Description',
      type: 'long-input',
      layout: 'full',
      placeholder: 'Service description or expense notes',
      condition: {
        field: 'operation',
        value: ['create_invoice', 'create_expense', 'create_time_entry'],
      },
    },
    {
      id: 'hours',
      title: 'Hours',
      type: 'short-input',
      layout: 'half',
      placeholder: '2.5',
      condition: { field: 'operation', value: 'create_time_entry' },
    },
    {
      id: 'date',
      title: 'Date',
      type: 'short-input',
      layout: 'half',
      placeholder: 'YYYY-MM-DD',
      condition: { field: 'operation', value: ['create_expense', 'create_time_entry'] },
    },
  ],
  tools: {
    access: ['freshbooks_api'],
    config: {
      tool: () => 'freshbooks_api',
      params: createParamTransformer({ amount: 'number', hours: 'number' }),
    },
  },
  inputs: {
    credential: { type: 'string', required: true },
    operation: { type: 'string', required: true },
    invoiceId: { type: 'string', required: false },
    clientId: { type: 'string', required: false },
    clientName: { type: 'string', required: false },
    email: { type: 'string', required: false },
    amount: { type: 'string', required: false },
    description: { type: 'string', required: false },
    hours: { type: 'string', required: false },
    date: { type: 'string', required: false },
  },
  outputs: {
    response: {
      type: {
        data: 'json',
      },
    },
  },
})
