import { FreshdeskIcon } from '@/components/icons'
import { createOperationDropdown, defineBlock } from '../helpers'

export const FreshdeskBlock = defineBlock({
  type: 'freshdesk',
  name: 'Freshdesk',
  description: 'Customer support software for better customer service.',
  longDescription:
    'Integrate with Freshdesk to manage customer support tickets, conversations, and knowledge base. Freshdesk is a cloud-based customer support platform that helps businesses provide exceptional customer service with ticketing, automation, self-service portals, and multichannel support. Perfect for managing customer inquiries across email, chat, phone, and social media.',
  category: 'tools',
  bgColor: '#2AB573',
  icon: FreshdeskIcon,
  subBlocks: [
    {
      id: 'credential',
      title: 'Freshdesk API Key',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter your Freshdesk API key',
      password: true,
    },
    {
      id: 'domain',
      title: 'Domain',
      type: 'short-input',
      layout: 'full',
      placeholder: 'your-company (from your-company.freshdesk.com)',
    },
    createOperationDropdown({
      operations: [
        { id: 'list_tickets', label: 'List Tickets' },
        { id: 'get_ticket', label: 'Get Ticket' },
        { id: 'create_ticket', label: 'Create Ticket' },
        { id: 'update_ticket', label: 'Update Ticket' },
        { id: 'delete_ticket', label: 'Delete Ticket' },
        { id: 'list_contacts', label: 'List Contacts' },
        { id: 'get_contact', label: 'Get Contact' },
        { id: 'create_contact', label: 'Create Contact' },
        { id: 'update_contact', label: 'Update Contact' },
        { id: 'list_conversations', label: 'List Conversations' },
        { id: 'create_note', label: 'Create Note' },
        { id: 'create_reply', label: 'Create Reply' },
      ],
      defaultValue: 'list_tickets',
    }),
    {
      id: 'ticketId',
      title: 'Ticket ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter ticket ID',
      condition: {
        field: 'operation',
        value: [
          'get_ticket',
          'update_ticket',
          'delete_ticket',
          'list_conversations',
          'create_note',
          'create_reply',
        ],
      },
    },
    {
      id: 'contactId',
      title: 'Contact ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter contact ID',
      condition: { field: 'operation', value: ['get_contact', 'update_contact'] },
    },
    {
      id: 'subject',
      title: 'Subject',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Ticket subject',
      condition: { field: 'operation', value: ['create_ticket', 'update_ticket'] },
    },
    {
      id: 'description',
      title: 'Description',
      type: 'long-input',
      layout: 'full',
      placeholder: 'Detailed description of the issue',
      condition: { field: 'operation', value: 'create_ticket' },
    },
    {
      id: 'priority',
      title: 'Priority',
      type: 'dropdown',
      layout: 'half',
      options: [
        { id: '1', label: 'Low' },
        { id: '2', label: 'Medium' },
        { id: '3', label: 'High' },
        { id: '4', label: 'Urgent' },
      ],
      value: () => '2',
      condition: { field: 'operation', value: ['create_ticket', 'update_ticket'] },
    },
    {
      id: 'status',
      title: 'Status',
      type: 'dropdown',
      layout: 'half',
      options: [
        { id: '2', label: 'Open' },
        { id: '3', label: 'Pending' },
        { id: '4', label: 'Resolved' },
        { id: '5', label: 'Closed' },
      ],
      value: () => '2',
      condition: { field: 'operation', value: ['create_ticket', 'update_ticket'] },
    },
    {
      id: 'email',
      title: 'Email',
      type: 'short-input',
      layout: 'half',
      placeholder: 'customer@example.com',
      condition: {
        field: 'operation',
        value: ['create_ticket', 'create_contact', 'update_contact'],
      },
    },
    {
      id: 'name',
      title: 'Name',
      type: 'short-input',
      layout: 'half',
      placeholder: 'John Doe',
      condition: { field: 'operation', value: ['create_contact', 'update_contact'] },
    },
    {
      id: 'phone',
      title: 'Phone',
      type: 'short-input',
      layout: 'half',
      placeholder: '+1234567890',
      condition: { field: 'operation', value: ['create_contact', 'update_contact'] },
    },
    {
      id: 'tags',
      title: 'Tags (comma separated)',
      type: 'short-input',
      layout: 'full',
      placeholder: 'bug,urgent,customer-issue',
      condition: { field: 'operation', value: ['create_ticket', 'update_ticket'] },
    },
    {
      id: 'noteBody',
      title: 'Note Body',
      type: 'long-input',
      layout: 'full',
      placeholder: 'Internal note content',
      condition: { field: 'operation', value: 'create_note' },
    },
    {
      id: 'replyBody',
      title: 'Reply Body',
      type: 'long-input',
      layout: 'full',
      placeholder: 'Reply to customer',
      condition: { field: 'operation', value: 'create_reply' },
    },
    {
      id: 'customFields',
      title: 'Custom Fields (JSON)',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: '{"custom_field_1": "value1"}',
      condition: {
        field: 'operation',
        value: ['create_ticket', 'update_ticket', 'create_contact', 'update_contact'],
      },
    },
  ],
  tools: {
    access: ['freshdesk_api'],
    config: {
      tool: () => 'freshdesk_api',
    },
  },
  inputs: {
    credential: { type: 'string', required: true },
    domain: { type: 'string', required: true },
    operation: { type: 'string', required: true },
    ticketId: { type: 'string', required: false },
    contactId: { type: 'string', required: false },
    subject: { type: 'string', required: false },
    description: { type: 'string', required: false },
    priority: { type: 'string', required: false },
    status: { type: 'string', required: false },
    email: { type: 'string', required: false },
    name: { type: 'string', required: false },
    phone: { type: 'string', required: false },
    tags: { type: 'string', required: false },
    noteBody: { type: 'string', required: false },
    replyBody: { type: 'string', required: false },
    customFields: { type: 'json', required: false },
  },
  outputs: {
    response: {
      type: {
        data: 'json',
      },
    },
  },
})
