import { GustoIcon } from '@/components/icons'
import { createOAuthSubBlock, createOperationDropdown, defineBlock } from '../helpers'

export const GustoBlock = defineBlock({
  type: 'gusto',
  name: 'Gusto',
  description: 'Modern payroll, benefits, and HR platform for small businesses.',
  longDescription:
    'Integrate with Gusto to manage payroll, employee benefits, time tracking, and HR administration. Gusto is a modern people platform that helps small and medium-sized businesses handle payroll, health insurance, 401(k) plans, and HR compliance. Perfect for automating employee onboarding, running payroll, and managing benefits.',
  category: 'tools',
  bgColor: '#F45D48',
  icon: GustoIcon,
  subBlocks: [
    createOAuthSubBlock({
      provider: 'gusto',
      serviceId: 'gusto',
      requiredScopes: [],
      title: 'Gusto Account',
      placeholder: 'Select Gusto account',
    }),
    createOperationDropdown({
      operations: [
        { id: 'list_companies', label: 'List Companies' },
        { id: 'get_company', label: 'Get Company' },
        { id: 'list_employees', label: 'List Employees' },
        { id: 'get_employee', label: 'Get Employee' },
        { id: 'create_employee', label: 'Create Employee' },
        { id: 'update_employee', label: 'Update Employee' },
        { id: 'list_payrolls', label: 'List Payrolls' },
        { id: 'get_payroll', label: 'Get Payroll' },
        { id: 'list_time_off_requests', label: 'List Time Off Requests' },
        { id: 'create_time_off_request', label: 'Create Time Off Request' },
      ],
      defaultValue: 'list_employees',
    }),
    {
      id: 'companyId',
      title: 'Company ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter company ID',
      condition: {
        field: 'operation',
        value: [
          'get_company',
          'list_employees',
          'create_employee',
          'list_payrolls',
          'list_time_off_requests',
          'create_time_off_request',
        ],
      },
    },
    {
      id: 'employeeId',
      title: 'Employee ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter employee ID',
      condition: { field: 'operation', value: ['get_employee', 'update_employee'] },
    },
    {
      id: 'payrollId',
      title: 'Payroll ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter payroll ID',
      condition: { field: 'operation', value: 'get_payroll' },
    },
    {
      id: 'firstName',
      title: 'First Name',
      type: 'short-input',
      layout: 'half',
      placeholder: 'John',
      condition: { field: 'operation', value: ['create_employee', 'update_employee'] },
    },
    {
      id: 'lastName',
      title: 'Last Name',
      type: 'short-input',
      layout: 'half',
      placeholder: 'Doe',
      condition: { field: 'operation', value: ['create_employee', 'update_employee'] },
    },
    {
      id: 'email',
      title: 'Email',
      type: 'short-input',
      layout: 'half',
      placeholder: 'john.doe@example.com',
      condition: { field: 'operation', value: ['create_employee', 'update_employee'] },
    },
    {
      id: 'dateOfBirth',
      title: 'Date of Birth',
      type: 'short-input',
      layout: 'half',
      placeholder: '1990-01-01',
      condition: { field: 'operation', value: ['create_employee', 'update_employee'] },
    },
    {
      id: 'ssn',
      title: 'SSN (Social Security Number)',
      type: 'short-input',
      layout: 'full',
      placeholder: '123-45-6789',
      password: true,
      condition: { field: 'operation', value: 'create_employee' },
    },
    {
      id: 'jobTitle',
      title: 'Job Title',
      type: 'short-input',
      layout: 'half',
      placeholder: 'Software Engineer',
      condition: { field: 'operation', value: ['create_employee', 'update_employee'] },
    },
    {
      id: 'hireDate',
      title: 'Hire Date',
      type: 'short-input',
      layout: 'half',
      placeholder: '2025-01-01',
      condition: { field: 'operation', value: ['create_employee', 'update_employee'] },
    },
    {
      id: 'timeOffType',
      title: 'Time Off Type',
      type: 'short-input',
      layout: 'half',
      placeholder: 'Vacation, Sick',
      condition: { field: 'operation', value: 'create_time_off_request' },
    },
    {
      id: 'startDate',
      title: 'Start Date',
      type: 'short-input',
      layout: 'half',
      placeholder: '2025-06-01',
      condition: { field: 'operation', value: 'create_time_off_request' },
    },
    {
      id: 'endDate',
      title: 'End Date',
      type: 'short-input',
      layout: 'half',
      placeholder: '2025-06-05',
      condition: { field: 'operation', value: 'create_time_off_request' },
    },
    {
      id: 'homeAddress',
      title: 'Home Address (JSON)',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder:
        '{"street": "123 Main St", "city": "San Francisco", "state": "CA", "zip": "94102"}',
      condition: { field: 'operation', value: ['create_employee', 'update_employee'] },
    },
  ],
  tools: {
    access: ['gusto_api'],
    config: {
      tool: () => 'gusto_api',
    },
  },
  inputs: {
    credential: { type: 'string', required: true },
    operation: { type: 'string', required: true },
    companyId: { type: 'string', required: false },
    employeeId: { type: 'string', required: false },
    payrollId: { type: 'string', required: false },
    firstName: { type: 'string', required: false },
    lastName: { type: 'string', required: false },
    email: { type: 'string', required: false },
    dateOfBirth: { type: 'string', required: false },
    ssn: { type: 'string', required: false },
    jobTitle: { type: 'string', required: false },
    hireDate: { type: 'string', required: false },
    timeOffType: { type: 'string', required: false },
    startDate: { type: 'string', required: false },
    endDate: { type: 'string', required: false },
    homeAddress: { type: 'json', required: false },
  },
  outputs: {
    response: {
      type: {
        data: 'json',
      },
    },
  },
})
