import { InteractiveBrokersIcon } from '@/components/icons'
import { createOperationDropdown, defineBlock } from '../helpers'

export const InteractiveBrokersBlock = defineBlock({
  type: 'interactive_brokers',
  name: 'Interactive Brokers',
  description: '⚠️ Stock, options, futures, and forex trading',
  longDescription:
    'Connect to Interactive Brokers API for professional trading across stocks, options, futures, forex, bonds, and funds. Access real-time market data, execute trades, manage portfolios, and retrieve account information. Supports multiple asset classes and global markets. Uses API key authentication with TWS/Gateway. ⚠️ REGULATORY NOTICE: This integration is for authorized use only. Trading carries substantial risk of loss. Users must comply with all applicable securities regulations, margin requirements, and trading rules. Professional trading requires proper licensing in many jurisdictions.',
  category: 'tools',
  bgColor: '#0077C8',
  icon: InteractiveBrokersIcon,
  subBlocks: [
    {
      id: 'apiKey',
      title: 'API Key / Client ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Your IB API Key',
      password: true,
      description: '⚠️ Requires TWS or IB Gateway running. Use paper trading for testing.',
    },
    {
      id: 'apiSecret',
      title: 'API Secret',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Your IB API Secret',
      password: true,
    },
    {
      id: 'paperTrading',
      title: 'Paper Trading',
      type: 'switch',
      layout: 'half',
      description: 'Enable for simulated trading',
    },
    createOperationDropdown({
      operations: [
        { id: 'get_accounts', label: 'Get Accounts' },
        { id: 'get_account_summary', label: 'Get Account Summary' },
        { id: 'get_positions', label: 'Get Positions' },
        { id: 'get_portfolio', label: 'Get Portfolio' },
        { id: 'get_cash_balance', label: 'Get Cash Balance' },
        { id: 'get_market_data', label: 'Get Market Data' },
        { id: 'get_historical_data', label: 'Get Historical Data' },
        { id: 'get_contract_details', label: 'Get Contract Details' },
        { id: 'search_contracts', label: 'Search Contracts' },
        { id: 'place_order', label: '⚠️ Place Order' },
        { id: 'modify_order', label: 'Modify Order' },
        { id: 'cancel_order', label: 'Cancel Order' },
        { id: 'get_open_orders', label: 'Get Open Orders' },
        { id: 'get_order_status', label: 'Get Order Status' },
        { id: 'get_executions', label: 'Get Executions' },
        { id: 'get_pnl', label: 'Get P&L' },
      ],
      defaultValue: 'get_account_summary',
    }),
    {
      id: 'accountId',
      title: 'Account ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Account number (optional)',
      condition: {
        field: 'operation',
        value: [
          'get_account_summary',
          'get_positions',
          'get_portfolio',
          'get_cash_balance',
          'place_order',
          'get_pnl',
        ],
      },
    },
    // Contract/Symbol fields
    {
      id: 'symbol',
      title: 'Symbol',
      type: 'short-input',
      layout: 'half',
      placeholder: 'AAPL, TSLA, SPY',
      condition: {
        field: 'operation',
        value: [
          'get_market_data',
          'get_historical_data',
          'get_contract_details',
          'search_contracts',
          'place_order',
        ],
      },
    },
    {
      id: 'secType',
      title: 'Security Type',
      type: 'dropdown',
      layout: 'half',
      options: [
        { id: 'STK', label: 'Stock' },
        { id: 'OPT', label: 'Option' },
        { id: 'FUT', label: 'Future' },
        { id: 'CASH', label: 'Forex' },
        { id: 'IND', label: 'Index' },
        { id: 'BOND', label: 'Bond' },
        { id: 'CFD', label: 'CFD' },
      ],
      condition: {
        field: 'operation',
        value: [
          'get_market_data',
          'get_historical_data',
          'get_contract_details',
          'search_contracts',
          'place_order',
        ],
      },
    },
    {
      id: 'exchange',
      title: 'Exchange',
      type: 'short-input',
      layout: 'half',
      placeholder: 'SMART, NASDAQ, NYSE',
      condition: {
        field: 'operation',
        value: ['get_market_data', 'get_contract_details', 'place_order'],
      },
    },
    {
      id: 'currency',
      title: 'Currency',
      type: 'short-input',
      layout: 'half',
      placeholder: 'USD, EUR, GBP',
      condition: {
        field: 'operation',
        value: ['get_market_data', 'get_contract_details', 'place_order'],
      },
    },
    // Historical data fields
    {
      id: 'duration',
      title: 'Duration',
      type: 'short-input',
      layout: 'half',
      placeholder: '1 D, 1 W, 1 M, 1 Y',
      condition: { field: 'operation', value: 'get_historical_data' },
    },
    {
      id: 'barSize',
      title: 'Bar Size',
      type: 'dropdown',
      layout: 'half',
      options: [
        { id: '1 min', label: '1 Minute' },
        { id: '5 mins', label: '5 Minutes' },
        { id: '15 mins', label: '15 Minutes' },
        { id: '1 hour', label: '1 Hour' },
        { id: '1 day', label: '1 Day' },
      ],
      condition: { field: 'operation', value: 'get_historical_data' },
    },
    // Order fields
    {
      id: 'action',
      title: 'Action',
      type: 'dropdown',
      layout: 'half',
      options: [
        { id: 'BUY', label: '🟢 BUY' },
        { id: 'SELL', label: '🔴 SELL' },
      ],
      condition: { field: 'operation', value: 'place_order' },
    },
    {
      id: 'orderType',
      title: 'Order Type',
      type: 'dropdown',
      layout: 'half',
      options: [
        { id: 'MKT', label: 'Market' },
        { id: 'LMT', label: 'Limit' },
        { id: 'STP', label: 'Stop' },
        { id: 'STP LMT', label: 'Stop Limit' },
        { id: 'TRAIL', label: 'Trailing Stop' },
      ],
      condition: { field: 'operation', value: 'place_order' },
    },
    {
      id: 'quantity',
      title: 'Quantity',
      type: 'short-input',
      layout: 'half',
      placeholder: '100',
      condition: { field: 'operation', value: 'place_order' },
    },
    {
      id: 'limitPrice',
      title: 'Limit Price',
      type: 'short-input',
      layout: 'half',
      placeholder: '150.00',
      condition: { field: 'operation', value: 'place_order' },
    },
    {
      id: 'stopPrice',
      title: 'Stop Price',
      type: 'short-input',
      layout: 'half',
      placeholder: '145.00',
      condition: { field: 'operation', value: 'place_order' },
    },
    {
      id: 'orderId',
      title: 'Order ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Order ID',
      condition: {
        field: 'operation',
        value: ['modify_order', 'cancel_order', 'get_order_status'],
      },
    },
  ],
  tools: {
    access: ['interactive_brokers_api'],
    config: {
      tool: () => 'interactive_brokers_api',
      params: (params) => {
        const { apiKey, apiSecret, paperTrading, ...rest } = params as Record<string, any>
        return {
          apiKey,
          apiSecret,
          paperTrading,
          ...rest,
        }
      },
    },
  },
  inputs: {
    apiKey: { type: 'string', required: true },
    apiSecret: { type: 'string', required: true },
    paperTrading: { type: 'boolean', required: false },
    operation: { type: 'string', required: true },
    accountId: { type: 'string', required: false },
    symbol: { type: 'string', required: false },
    secType: { type: 'string', required: false },
    exchange: { type: 'string', required: false },
    currency: { type: 'string', required: false },
    duration: { type: 'string', required: false },
    barSize: { type: 'string', required: false },
    action: { type: 'string', required: false },
    orderType: { type: 'string', required: false },
    quantity: { type: 'string', required: false },
    limitPrice: { type: 'string', required: false },
    stopPrice: { type: 'string', required: false },
    orderId: { type: 'string', required: false },
  },
  outputs: {
    response: {
      type: {
        success: 'boolean',
        data: 'any',
      },
    },
  },
  compliance: {
    enabled: true,
    tags: ['financial_trading', 'high_risk', 'regulated', 'region_restricted'],
    disclaimer:
      'REGULATORY NOTICE: Professional securities trading carries substantial risk of loss. This block is intended for authorized use only. Users must comply with all applicable securities regulations, margin requirements, FINRA rules, and trading laws. Interactive Brokers is a regulated broker-dealer subject to oversight by multiple financial authorities. Professional trading may require licensing (Series 7, Series 63, etc.) in many jurisdictions. Margin trading, options, futures, and forex involve significant risk. Users are solely responsible for ensuring compliance with all applicable laws and regulations.',
    restrictedRegions: ['Varies by product and jurisdiction'],
    requiresLicense: true,
    riskLevel: 'high',
  },
})
