import { MailchimpIcon } from '@/components/icons'
import { createOperationDropdown, defineBlock } from '../helpers'

export const MailchimpBlock = defineBlock({
  type: 'mailchimp',
  name: 'Mailchimp',
  description: 'Email marketing with Mailchimp audiences and campaigns.',
  longDescription:
    'Connect to Mailchimp Marketing API 3.0 to manage audiences, subscribers, and email campaigns.',
  category: 'tools',
  bgColor: '#FFE01B',
  icon: MailchimpIcon,
  subBlocks: [
    {
      id: 'apiKey',
      title: 'API Key',
      type: 'short-input',
      layout: 'half',
      placeholder: 'xxxxxxxx-usX',
      password: true,
    },
    {
      id: 'serverPrefix',
      title: 'Server Prefix',
      type: 'short-input',
      layout: 'half',
      placeholder: 'us1, us21, etc.',
    },
    createOperationDropdown({
      operations: [
        { id: 'list_audiences', label: 'List Audiences' },
        { id: 'get_audience', label: 'Get Audience' },
        { id: 'list_members', label: 'List Members' },
        { id: 'add_member', label: 'Add Member' },
        { id: 'update_member', label: 'Update Member' },
        { id: 'list_campaigns', label: 'List Campaigns' },
        { id: 'create_campaign', label: 'Create Campaign' },
        { id: 'send_campaign', label: 'Send Campaign' },
      ],
    }),
    {
      id: 'audienceId',
      title: 'Audience ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Audience/List ID',
      condition: {
        field: 'operation',
        value: ['get_audience', 'list_members', 'add_member', 'update_member', 'create_campaign'],
      },
    },
    {
      id: 'email',
      title: 'Email',
      type: 'short-input',
      layout: 'half',
      placeholder: 'subscriber@example.com',
      condition: { field: 'operation', value: ['add_member', 'update_member'] },
    },
    {
      id: 'status',
      title: 'Status',
      type: 'dropdown',
      layout: 'half',
      options: [
        { label: 'Subscribed', id: 'subscribed' },
        { label: 'Pending', id: 'pending' },
        { label: 'Unsubscribed', id: 'unsubscribed' },
      ],
      condition: { field: 'operation', value: ['add_member', 'update_member'] },
    },
    {
      id: 'firstName',
      title: 'First Name',
      type: 'short-input',
      layout: 'half',
      placeholder: 'John',
      condition: { field: 'operation', value: ['add_member', 'update_member'] },
    },
    {
      id: 'lastName',
      title: 'Last Name',
      type: 'short-input',
      layout: 'half',
      placeholder: 'Doe',
      condition: { field: 'operation', value: ['add_member', 'update_member'] },
    },
    {
      id: 'campaignId',
      title: 'Campaign ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Campaign ID',
      condition: { field: 'operation', value: 'send_campaign' },
    },
    {
      id: 'campaignTitle',
      title: 'Campaign Title',
      type: 'short-input',
      layout: 'full',
      placeholder: 'My Campaign',
      condition: { field: 'operation', value: 'create_campaign' },
    },
    {
      id: 'subjectLine',
      title: 'Subject Line',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Email subject',
      condition: { field: 'operation', value: 'create_campaign' },
    },
    {
      id: 'fromName',
      title: 'From Name',
      type: 'short-input',
      layout: 'half',
      placeholder: 'Your Company',
      condition: { field: 'operation', value: 'create_campaign' },
    },
    {
      id: 'replyTo',
      title: 'Reply-To Email',
      type: 'short-input',
      layout: 'half',
      placeholder: 'reply@example.com',
      condition: { field: 'operation', value: 'create_campaign' },
    },
  ],
  tools: {
    access: ['mailchimp_marketing'],
    config: {
      tool: () => 'mailchimp_marketing',
    },
  },
  inputs: {
    operation: { type: 'string', required: true },
    apiKey: { type: 'string', required: true },
    serverPrefix: { type: 'string', required: true },
    audienceId: { type: 'string', required: false },
    email: { type: 'string', required: false },
    firstName: { type: 'string', required: false },
    lastName: { type: 'string', required: false },
    status: { type: 'string', required: false },
    campaignId: { type: 'string', required: false },
    campaignTitle: { type: 'string', required: false },
    subjectLine: { type: 'string', required: false },
    fromName: { type: 'string', required: false },
    replyTo: { type: 'string', required: false },
  },
  outputs: {
    response: {
      type: {
        success: 'boolean',
        data: 'any',
      },
    },
  },
})
