import { PostmarkIcon } from '@/components/icons'
import { BlockConfig } from '../types'

export const PostmarkBlock: BlockConfig = {
  type: 'postmark',
  name: 'Postmark',
  description: 'Fast and reliable transactional email delivery service.',
  longDescription:
    'Integrate with Postmark for reliable transactional email delivery with industry-leading speed and deliverability. Postmark specializes in sending application emails with powerful APIs, beautiful templates, detailed analytics, and world-class support. Perfect for password resets, receipts, and notifications.',
  category: 'tools',
  bgColor: '#FFCD00',
  icon: PostmarkIcon,
  subBlocks: [
    {
      id: 'credential',
      title: 'Postmark Server Token',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter your Postmark server API token',
      password: true,
    },
    {
      id: 'accountToken',
      title: 'Account Token (Optional)',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter your Postmark account API token',
      password: true,
    },
    {
      id: 'operation',
      title: 'Operation',
      type: 'dropdown',
      layout: 'full',
      options: [
        { id: 'send_email', label: 'Send Email' },
        { id: 'send_batch', label: 'Send Batch Emails' },
        { id: 'send_template', label: 'Send with Template' },
        { id: 'get_bounces', label: 'Get Bounces' },
        { id: 'get_stats', label: 'Get Stats' },
      ],
      value: () => 'send_email',
    },
    {
      id: 'from',
      title: 'From',
      type: 'short-input',
      layout: 'half',
      placeholder: 'sender@yourdomain.com',
      condition: { field: 'operation', value: ['send_email', 'send_batch', 'send_template'] },
    },
    {
      id: 'to',
      title: 'To',
      type: 'short-input',
      layout: 'half',
      placeholder: 'recipient@example.com',
      condition: { field: 'operation', value: ['send_email', 'send_template'] },
    },
    {
      id: 'subject',
      title: 'Subject',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Email subject',
      condition: { field: 'operation', value: ['send_email', 'send_batch'] },
    },
    {
      id: 'textBody',
      title: 'Text Body',
      type: 'long-input',
      layout: 'full',
      placeholder: 'Plain text email body',
      condition: { field: 'operation', value: ['send_email', 'send_batch'] },
    },
    {
      id: 'htmlBody',
      title: 'HTML Body',
      type: 'code',
      layout: 'full',
      language: 'text',
      placeholder: '<html><body>HTML email content</body></html>',
      condition: { field: 'operation', value: ['send_email', 'send_batch'] },
    },
    {
      id: 'templateId',
      title: 'Template ID',
      type: 'short-input',
      layout: 'half',
      placeholder: '12345',
      condition: { field: 'operation', value: 'send_template' },
    },
    {
      id: 'templateModel',
      title: 'Template Model (JSON)',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: '{"name": "John", "product": "Premium Plan"}',
      condition: { field: 'operation', value: 'send_template' },
    },
    {
      id: 'messageStream',
      title: 'Message Stream',
      type: 'short-input',
      layout: 'full',
      placeholder: 'outbound (default)',
      condition: { field: 'operation', value: ['send_email', 'send_batch', 'send_template'] },
    },
  ],
  tools: {
    access: ['postmark_api'],
    config: {
      tool: () => 'postmark_api',
    },
  },
  inputs: {
    credential: { type: 'string', required: true },
    accountToken: { type: 'string', required: false },
    operation: { type: 'string', required: true },
    from: { type: 'string', required: false },
    to: { type: 'string', required: false },
    subject: { type: 'string', required: false },
    textBody: { type: 'string', required: false },
    htmlBody: { type: 'string', required: false },
    templateId: { type: 'string', required: false },
    templateModel: { type: 'json', required: false },
    messageStream: { type: 'string', required: false },
  },
  outputs: {
    response: {
      type: {
        data: 'json',
      },
    },
  },
}
