import { SendGridIcon } from '@/components/icons'
import { createOperationDropdown, defineBlock } from '../helpers'

export const SendGridBlock = defineBlock({
  type: 'sendgrid',
  name: 'SendGrid',
  description: 'Send emails and manage contacts with SendGrid.',
  longDescription:
    'Connect to SendGrid API v3 to send transactional emails, use dynamic templates, and manage marketing contacts.',
  category: 'tools',
  bgColor: '#1A82E2',
  icon: SendGridIcon,
  subBlocks: [
    {
      id: 'apiKey',
      title: 'API Key',
      type: 'short-input',
      layout: 'full',
      placeholder: 'SG.xxxxxxxx',
      password: true,
    },
    createOperationDropdown({
      operations: [
        { id: 'send_email', label: 'Send Email' },
        { id: 'send_template', label: 'Send Template Email' },
        { id: 'list_contacts', label: 'List Contacts' },
        { id: 'add_contact', label: 'Add Contact' },
      ],
    }),
    {
      id: 'from',
      title: 'From Email',
      type: 'short-input',
      layout: 'half',
      placeholder: 'sender@example.com',
      condition: { field: 'operation', value: ['send_email', 'send_template'] },
    },
    {
      id: 'fromName',
      title: 'From Name',
      type: 'short-input',
      layout: 'half',
      placeholder: 'Sender Name',
      condition: { field: 'operation', value: ['send_email', 'send_template'] },
    },
    {
      id: 'to',
      title: 'To Email(s)',
      type: 'short-input',
      layout: 'full',
      placeholder: 'recipient@example.com (comma-separated for multiple)',
      condition: { field: 'operation', value: ['send_email', 'send_template'] },
    },
    {
      id: 'subject',
      title: 'Subject',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Email subject line',
      condition: { field: 'operation', value: 'send_email' },
    },
    {
      id: 'htmlContent',
      title: 'HTML Content',
      type: 'code',
      layout: 'full',
      placeholder: '<h1>Hello!</h1><p>Your message here...</p>',
      condition: { field: 'operation', value: 'send_email' },
    },
    {
      id: 'textContent',
      title: 'Plain Text (optional)',
      type: 'long-input',
      layout: 'full',
      placeholder: 'Plain text version of your email',
      condition: { field: 'operation', value: 'send_email' },
    },
    {
      id: 'templateId',
      title: 'Template ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'd-xxxxxxxxxxxxxxxx',
      condition: { field: 'operation', value: 'send_template' },
    },
    {
      id: 'dynamicTemplateData',
      title: 'Template Data (JSON)',
      type: 'code',
      layout: 'full',
      placeholder: '{"name": "John", "orderNumber": "12345"}',
      condition: { field: 'operation', value: 'send_template' },
    },
    {
      id: 'email',
      title: 'Contact Email',
      type: 'short-input',
      layout: 'full',
      placeholder: 'contact@example.com',
      condition: { field: 'operation', value: 'add_contact' },
    },
    {
      id: 'firstName',
      title: 'First Name',
      type: 'short-input',
      layout: 'half',
      placeholder: 'John',
      condition: { field: 'operation', value: 'add_contact' },
    },
    {
      id: 'lastName',
      title: 'Last Name',
      type: 'short-input',
      layout: 'half',
      placeholder: 'Doe',
      condition: { field: 'operation', value: 'add_contact' },
    },
  ],
  tools: {
    access: ['sendgrid_send'],
    config: {
      tool: () => 'sendgrid_send',
    },
  },
  inputs: {
    operation: { type: 'string', required: true },
    apiKey: { type: 'string', required: true },
    to: { type: 'string', required: false },
    from: { type: 'string', required: false },
    fromName: { type: 'string', required: false },
    subject: { type: 'string', required: false },
    htmlContent: { type: 'string', required: false },
    textContent: { type: 'string', required: false },
    templateId: { type: 'string', required: false },
    dynamicTemplateData: { type: 'json', required: false },
    email: { type: 'string', required: false },
    firstName: { type: 'string', required: false },
    lastName: { type: 'string', required: false },
  },
  outputs: {
    response: {
      type: {
        success: 'boolean',
        messageId: 'string',
        data: 'any',
      },
    },
  },
})
