import { PlayButtonIcon } from '@/components/icons'
import { ToolResponse } from '@/tools/types'
import { BlockConfig } from '../types'

interface StarterBlockOutput extends ToolResponse {
  output: {
    input: any
  }
}

export const StarterBlock: BlockConfig<StarterBlockOutput> = {
  type: 'starter',
  name: 'Starter',
  description: 'Start workflow',
  longDescription:
    'Start your workflow with multiple trigger options: manual execution, scheduled runs, real-time webhooks, email monitoring, form submissions, database changes, file operations, calendar events, and API polling. Configure flexible execution patterns with customizable timing, security, and integration options.',
  category: 'blocks',
  bgColor: '#2FB3FF',
  icon: PlayButtonIcon,
  subBlocks: [
    // Main trigger selector
    {
      id: 'startWorkflow',
      title: 'Start Workflow',
      type: 'dropdown',
      layout: 'full',
      options: [
        {
          label: 'Run manually',
          id: 'manual',
          group: 'manual',
          icon: 'mouse-pointer-2',
          description: 'Start workflow manually or via API call',
        },
        {
          label: 'On webhook call',
          id: 'webhook',
          group: 'real-time',
          icon: 'webhook',
          description: 'Trigger when webhook receives data from external services',
        },
        {
          label: 'On email received',
          id: 'email',
          group: 'real-time',
          icon: 'mail',
          description: 'Start when new email arrives in specified folder',
        },
        {
          label: 'On form submission',
          id: 'form',
          group: 'real-time',
          icon: 'file-text',
          description: 'Trigger on new form responses from Google Forms, Typeform, etc.',
        },
        {
          label: 'On database change',
          id: 'database',
          group: 'real-time',
          icon: 'database',
          description: 'Start when data changes in Sheets, Airtable, or databases',
        },
        {
          label: 'On file upload/change',
          id: 'file',
          group: 'real-time',
          icon: 'cloud-upload',
          description: 'Trigger when files are added or modified in cloud storage',
        },
        {
          label: 'On calendar event',
          id: 'calendar',
          group: 'real-time',
          icon: 'calendar',
          description: 'Start based on calendar events from Google, Outlook, etc.',
        },
        {
          label: 'On schedule',
          id: 'schedule',
          group: 'scheduled',
          icon: 'clock',
          description: 'Run workflow at specific times or intervals',
        },
        {
          label: 'On API polling',
          id: 'polling',
          group: 'scheduled',
          icon: 'refresh-cw',
          description: 'Periodically check an API endpoint for new data',
        },
      ],
      value: () => 'manual',
    },
    // Structured Input format - visible if manual run is selected
    // {
    //   id: 'inputFormat',
    //   title: 'Input Format (for API calls)',
    //   type: 'input-format',
    //   layout: 'full',
    //   condition: { field: 'startWorkflow', value: 'manual' },
    // },
    // Webhook configuration
    {
      id: 'webhookProvider',
      title: 'Webhook Provider',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Slack', id: 'slack' },
        { label: 'Microsoft Teams', id: 'teams' },
        { label: 'Jira', id: 'jira' },
        { label: 'WhatsApp', id: 'whatsapp' },
        { label: 'GitHub', id: 'github' },
        { label: 'Discord', id: 'discord' },
        { label: 'Telegram', id: 'telegram' },
        { label: 'Airtable', id: 'airtable' },
        { label: 'Stripe', id: 'stripe' },
        { label: 'Generic', id: 'generic' },
      ],
      value: () => 'generic',
      condition: { field: 'startWorkflow', value: 'webhook' },
    },
    {
      id: 'webhookConfig',
      title: 'Webhook Configuration',
      type: 'webhook-config',
      layout: 'full',
      condition: { field: 'startWorkflow', value: 'webhook' },
    },
    // Schedule configuration status display
    {
      id: 'scheduleConfig',
      title: 'Schedule Status',
      type: 'schedule-config',
      layout: 'full',
      condition: { field: 'startWorkflow', value: 'schedule' },
    },
    // Hidden fields for schedule configuration (used by the modal only)
    {
      id: 'scheduleType',
      title: 'Frequency',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Every X Minutes', id: 'minutes' },
        { label: 'Hourly', id: 'hourly' },
        { label: 'Daily', id: 'daily' },
        { label: 'Weekly', id: 'weekly' },
        { label: 'Monthly', id: 'monthly' },
        { label: 'Custom Cron', id: 'custom' },
      ],
      value: () => 'daily',
      hidden: true,
      condition: { field: 'startWorkflow', value: 'schedule' },
    },
    {
      id: 'scheduleStartAt',
      type: 'date-input',
      hidden: true,
      condition: { field: 'startWorkflow', value: 'schedule' },
    },
    {
      id: 'scheduleTime',
      type: 'time-input',
      hidden: true,
      condition: { field: 'startWorkflow', value: 'schedule' },
    },
    {
      id: 'minutesInterval',
      type: 'short-input',
      hidden: true,
      condition: { field: 'startWorkflow', value: 'schedule' },
    },
    {
      id: 'hourlyMinute',
      type: 'short-input',
      hidden: true,
      condition: { field: 'startWorkflow', value: 'schedule' },
    },
    {
      id: 'dailyTime',
      type: 'short-input',
      hidden: true,
      condition: { field: 'startWorkflow', value: 'schedule' },
    },
    {
      id: 'weeklyDay',
      type: 'dropdown',
      hidden: true,
      options: [
        { label: 'Monday', id: 'MON' },
        { label: 'Tuesday', id: 'TUE' },
        { label: 'Wednesday', id: 'WED' },
        { label: 'Thursday', id: 'THU' },
        { label: 'Friday', id: 'FRI' },
        { label: 'Saturday', id: 'SAT' },
        { label: 'Sunday', id: 'SUN' },
      ],
      value: () => 'MON',
      condition: { field: 'startWorkflow', value: 'schedule' },
    },
    {
      id: 'weeklyDayTime',
      type: 'short-input',
      hidden: true,
      condition: { field: 'startWorkflow', value: 'schedule' },
    },
    {
      id: 'monthlyDay',
      type: 'short-input',
      hidden: true,
      condition: { field: 'startWorkflow', value: 'schedule' },
    },
    {
      id: 'monthlyTime',
      type: 'short-input',
      hidden: true,
      condition: { field: 'startWorkflow', value: 'schedule' },
    },
    {
      id: 'cronExpression',
      type: 'short-input',
      hidden: true,
      condition: { field: 'startWorkflow', value: 'schedule' },
    },
    {
      id: 'timezone',
      type: 'dropdown',
      hidden: true,
      options: [
        { label: 'UTC', id: 'UTC' },
        { label: 'US Eastern (UTC-4)', id: 'America/New_York' },
        { label: 'US Central (UTC-5)', id: 'America/Chicago' },
        { label: 'US Mountain (UTC-6)', id: 'America/Denver' },
        { label: 'US Pacific (UTC-7)', id: 'America/Los_Angeles' },
        { label: 'London (UTC+1)', id: 'Europe/London' },
        { label: 'Paris (UTC+2)', id: 'Europe/Paris' },
        { label: 'Singapore (UTC+8)', id: 'Asia/Singapore' },
        { label: 'Tokyo (UTC+9)', id: 'Asia/Tokyo' },
        { label: 'Sydney (UTC+10)', id: 'Australia/Sydney' },
      ],
      value: () => 'UTC',
      condition: { field: 'startWorkflow', value: 'schedule' },
    },
    // Email trigger configuration
    {
      id: 'emailProvider',
      title: 'Email Provider',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Gmail', id: 'gmail' },
        { label: 'Outlook', id: 'outlook' },
        { label: 'IMAP (Generic)', id: 'imap' },
      ],
      value: () => 'gmail',
      condition: { field: 'startWorkflow', value: 'email' },
    },
    {
      id: 'emailCredential',
      title: 'Gmail Account',
      type: 'oauth-input',
      layout: 'full',
      provider: 'google-email',
      serviceId: 'gmail',
      requiredScopes: [
        'https://www.googleapis.com/auth/gmail.readonly',
        'https://www.googleapis.com/auth/gmail.modify',
      ],
      placeholder: 'Select Gmail account',
      condition: {
        field: 'startWorkflow',
        value: 'email',
        and: { field: 'emailProvider', value: 'gmail' },
      },
    },
    {
      id: 'emailOutlookCredential',
      title: 'Outlook Account',
      type: 'oauth-input',
      layout: 'full',
      provider: 'microsoft',
      serviceId: 'microsoft-outlook',
      placeholder: 'Select Outlook account',
      condition: {
        field: 'startWorkflow',
        value: 'email',
        and: { field: 'emailProvider', value: 'outlook' },
      },
    },
    {
      id: 'emailPollingInterval',
      title: 'Check Interval',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Every 1 minute', id: '1' },
        { label: 'Every 5 minutes', id: '5' },
        { label: 'Every 15 minutes', id: '15' },
        { label: 'Every 30 minutes', id: '30' },
        { label: 'Every 60 minutes', id: '60' },
      ],
      value: () => '5',
      condition: { field: 'startWorkflow', value: 'email' },
    },
    {
      id: 'emailFolder',
      title: 'Folder/Label',
      type: 'short-input',
      layout: 'full',
      placeholder: 'INBOX',
      condition: { field: 'startWorkflow', value: 'email' },
    },
    {
      id: 'emailFilter',
      title: 'Email Filter (Optional)',
      type: 'short-input',
      layout: 'full',
      placeholder: 'from:someone@example.com subject:urgent',
      condition: { field: 'startWorkflow', value: 'email' },
    },
    // Form trigger configuration
    {
      id: 'formProvider',
      title: 'Form Provider',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Google Forms', id: 'google_forms' },
        { label: 'Typeform', id: 'typeform' },
        { label: 'Jotform', id: 'jotform' },
        { label: 'Microsoft Forms', id: 'ms_forms' },
        { label: 'Custom Form', id: 'custom' },
      ],
      value: () => 'google_forms',
      condition: { field: 'startWorkflow', value: 'form' },
    },
    {
      id: 'formCredential',
      title: 'Google Forms Account',
      type: 'oauth-input',
      layout: 'full',
      provider: 'google',
      serviceId: 'google-forms',
      placeholder: 'Select Google Forms account',
      condition: {
        field: 'startWorkflow',
        value: 'form',
        and: { field: 'formProvider', value: 'google_forms' },
      },
    },
    {
      id: 'formId',
      title: 'Form ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter form ID or URL',
      condition: { field: 'startWorkflow', value: 'form' },
    },
    {
      id: 'formPollingInterval',
      title: 'Check Interval',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Every 1 minute', id: '1' },
        { label: 'Every 5 minutes', id: '5' },
        { label: 'Every 15 minutes', id: '15' },
        { label: 'Every 30 minutes', id: '30' },
        { label: 'Every 60 minutes', id: '60' },
      ],
      value: () => '5',
      condition: { field: 'startWorkflow', value: 'form' },
    },
    // Database trigger configuration
    {
      id: 'databaseProvider',
      title: 'Database Provider',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Google Sheets', id: 'google_sheets' },
        { label: 'Airtable', id: 'airtable' },
        { label: 'Notion', id: 'notion' },
        { label: 'PostgreSQL', id: 'postgresql' },
        { label: 'MySQL', id: 'mysql' },
        { label: 'MongoDB', id: 'mongodb' },
      ],
      value: () => 'google_sheets',
      condition: { field: 'startWorkflow', value: 'database' },
    },
    {
      id: 'databaseCredential',
      title: 'Google Sheets Account',
      type: 'oauth-input',
      layout: 'full',
      provider: 'google',
      serviceId: 'google-sheets',
      placeholder: 'Select Google Sheets account',
      condition: {
        field: 'startWorkflow',
        value: 'database',
        and: { field: 'databaseProvider', value: 'google_sheets' },
      },
    },
    {
      id: 'databaseAirtableCredential',
      title: 'Airtable Account',
      type: 'oauth-input',
      layout: 'full',
      provider: 'airtable',
      serviceId: 'airtable',
      placeholder: 'Select Airtable account',
      condition: {
        field: 'startWorkflow',
        value: 'database',
        and: { field: 'databaseProvider', value: 'airtable' },
      },
    },
    {
      id: 'databaseNotionCredential',
      title: 'Notion Account',
      type: 'oauth-input',
      layout: 'full',
      provider: 'notion',
      serviceId: 'notion',
      placeholder: 'Select Notion account',
      condition: {
        field: 'startWorkflow',
        value: 'database',
        and: { field: 'databaseProvider', value: 'notion' },
      },
    },
    {
      id: 'databaseResource',
      title: 'Resource ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Sheet ID, Table ID, or Database name',
      condition: { field: 'startWorkflow', value: 'database' },
    },
    {
      id: 'databaseTriggerType',
      title: 'Trigger On',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'New Row/Record', id: 'insert' },
        { label: 'Updated Row/Record', id: 'update' },
        { label: 'Deleted Row/Record', id: 'delete' },
        { label: 'Any Change', id: 'any' },
      ],
      value: () => 'insert',
      condition: { field: 'startWorkflow', value: 'database' },
    },
    {
      id: 'databasePollingInterval',
      title: 'Check Interval',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Every 1 minute', id: '1' },
        { label: 'Every 5 minutes', id: '5' },
        { label: 'Every 15 minutes', id: '15' },
        { label: 'Every 30 minutes', id: '30' },
        { label: 'Every 60 minutes', id: '60' },
      ],
      value: () => '5',
      condition: { field: 'startWorkflow', value: 'database' },
    },
    // File trigger configuration
    {
      id: 'fileProvider',
      title: 'File Storage Provider',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Google Drive', id: 'google_drive' },
        { label: 'Dropbox', id: 'dropbox' },
        { label: 'OneDrive', id: 'onedrive' },
        { label: 'AWS S3', id: 's3' },
        { label: 'Box', id: 'box' },
      ],
      value: () => 'google_drive',
      condition: { field: 'startWorkflow', value: 'file' },
    },
    {
      id: 'fileCredential',
      title: 'Google Drive Account',
      type: 'oauth-input',
      layout: 'full',
      provider: 'google',
      serviceId: 'google-drive',
      placeholder: 'Select Google Drive account',
      condition: {
        field: 'startWorkflow',
        value: 'file',
        and: { field: 'fileProvider', value: 'google_drive' },
      },
    },
    {
      id: 'fileOneDriveCredential',
      title: 'OneDrive Account',
      type: 'oauth-input',
      layout: 'full',
      provider: 'microsoft',
      serviceId: 'microsoft-onedrive',
      placeholder: 'Select OneDrive account',
      condition: {
        field: 'startWorkflow',
        value: 'file',
        and: { field: 'fileProvider', value: 'onedrive' },
      },
    },
    {
      id: 'filePath',
      title: 'Folder Path',
      type: 'short-input',
      layout: 'full',
      placeholder: '/uploads or folder ID',
      condition: { field: 'startWorkflow', value: 'file' },
    },
    {
      id: 'fileTriggerType',
      title: 'Trigger On',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'File Created', id: 'created' },
        { label: 'File Modified', id: 'modified' },
        { label: 'File Deleted', id: 'deleted' },
        { label: 'Any Change', id: 'any' },
      ],
      value: () => 'created',
      condition: { field: 'startWorkflow', value: 'file' },
    },
    {
      id: 'fileFilter',
      title: 'File Filter (Optional)',
      type: 'short-input',
      layout: 'full',
      placeholder: '*.pdf, *.jpg, *.csv',
      condition: { field: 'startWorkflow', value: 'file' },
    },
    {
      id: 'filePollingInterval',
      title: 'Check Interval',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Every 1 minute', id: '1' },
        { label: 'Every 5 minutes', id: '5' },
        { label: 'Every 15 minutes', id: '15' },
        { label: 'Every 30 minutes', id: '30' },
        { label: 'Every 60 minutes', id: '60' },
      ],
      value: () => '5',
      condition: { field: 'startWorkflow', value: 'file' },
    },
    // Calendar trigger configuration
    {
      id: 'calendarProvider',
      title: 'Calendar Provider',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Google Calendar', id: 'google_calendar' },
        { label: 'Outlook Calendar', id: 'outlook_calendar' },
        { label: 'iCloud Calendar', id: 'icloud_calendar' },
      ],
      value: () => 'google_calendar',
      condition: { field: 'startWorkflow', value: 'calendar' },
    },
    {
      id: 'calendarCredential',
      title: 'Google Calendar Account',
      type: 'oauth-input',
      layout: 'full',
      provider: 'google',
      serviceId: 'google-calendar',
      placeholder: 'Select Google Calendar account',
      condition: {
        field: 'startWorkflow',
        value: 'calendar',
        and: { field: 'calendarProvider', value: 'google_calendar' },
      },
    },
    {
      id: 'calendarOutlookCredential',
      title: 'Outlook Calendar Account',
      type: 'oauth-input',
      layout: 'full',
      provider: 'microsoft',
      serviceId: 'microsoft-outlook',
      placeholder: 'Select Outlook Calendar account',
      condition: {
        field: 'startWorkflow',
        value: 'calendar',
        and: { field: 'calendarProvider', value: 'outlook_calendar' },
      },
    },
    {
      id: 'calendarId',
      title: 'Calendar ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'primary or calendar ID',
      condition: { field: 'startWorkflow', value: 'calendar' },
    },
    {
      id: 'calendarTriggerType',
      title: 'Trigger On',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Event Created', id: 'created' },
        { label: 'Event Updated', id: 'updated' },
        { label: 'Event Starts (Before X minutes)', id: 'starts' },
        { label: 'Event Ends', id: 'ends' },
      ],
      value: () => 'created',
      condition: { field: 'startWorkflow', value: 'calendar' },
    },
    {
      id: 'calendarMinutesBefore',
      title: 'Minutes Before Event',
      type: 'short-input',
      layout: 'full',
      placeholder: '15',
      condition: { field: 'startWorkflow', value: 'calendar' },
      hidden: true,
    },
    {
      id: 'calendarPollingInterval',
      title: 'Check Interval',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Every 1 minute', id: '1' },
        { label: 'Every 5 minutes', id: '5' },
        { label: 'Every 15 minutes', id: '15' },
        { label: 'Every 30 minutes', id: '30' },
        { label: 'Every 60 minutes', id: '60' },
      ],
      value: () => '5',
      condition: { field: 'startWorkflow', value: 'calendar' },
    },
    // Polling trigger configuration
    {
      id: 'pollingUrl',
      title: 'API Endpoint URL',
      type: 'short-input',
      layout: 'full',
      placeholder: 'https://api.example.com/data',
      condition: { field: 'startWorkflow', value: 'polling' },
    },
    {
      id: 'pollingMethod',
      title: 'HTTP Method',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'GET', id: 'GET' },
        { label: 'POST', id: 'POST' },
      ],
      value: () => 'GET',
      condition: { field: 'startWorkflow', value: 'polling' },
    },
    {
      id: 'pollingInterval',
      title: 'Polling Interval',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Every 1 minute', id: '1' },
        { label: 'Every 5 minutes', id: '5' },
        { label: 'Every 15 minutes', id: '15' },
        { label: 'Every 30 minutes', id: '30' },
        { label: 'Every hour', id: '60' },
      ],
      value: () => '5',
      condition: { field: 'startWorkflow', value: 'polling' },
    },
    {
      id: 'pollingHeaders',
      title: 'HTTP Headers (JSON)',
      type: 'long-input',
      layout: 'full',
      placeholder: '{"Authorization": "Bearer token", "Content-Type": "application/json"}',
      condition: { field: 'startWorkflow', value: 'polling' },
    },
    {
      id: 'pollingBody',
      title: 'Request Body (JSON)',
      type: 'long-input',
      layout: 'full',
      placeholder: '{"key": "value"}',
      condition: { field: 'startWorkflow', value: 'polling' },
    },
    {
      id: 'pollingIdentifierPath',
      title: 'Unique Identifier Path',
      type: 'short-input',
      layout: 'full',
      placeholder: 'data.id or items[].uuid',
      condition: { field: 'startWorkflow', value: 'polling' },
    },
  ],
  tools: {
    access: [],
  },
  inputs: {
    input: { type: 'json', required: false },
    startWorkflow: { type: 'string', required: true },
    // Webhook inputs
    webhookProvider: { type: 'string', required: false },
    webhookPath: { type: 'string', required: false },
    providerConfig: { type: 'json', required: false },
    // Schedule inputs
    scheduleType: { type: 'string', required: false },
    scheduleStartAt: { type: 'string', required: false },
    scheduleTime: { type: 'string', required: false },
    minutesInterval: { type: 'string', required: false },
    hourlyMinute: { type: 'string', required: false },
    dailyTime: { type: 'string', required: false },
    weeklyDay: { type: 'string', required: false },
    weeklyDayTime: { type: 'string', required: false },
    monthlyDay: { type: 'string', required: false },
    monthlyTime: { type: 'string', required: false },
    cronExpression: { type: 'string', required: false },
    timezone: { type: 'string', required: false },
    // Email inputs
    emailProvider: { type: 'string', required: false },
    emailCredential: { type: 'string', required: false },
    emailOutlookCredential: { type: 'string', required: false },
    emailPollingInterval: { type: 'string', required: false },
    emailFolder: { type: 'string', required: false },
    emailFilter: { type: 'string', required: false },
    // Form inputs
    formProvider: { type: 'string', required: false },
    formCredential: { type: 'string', required: false },
    formId: { type: 'string', required: false },
    formPollingInterval: { type: 'string', required: false },
    // Database inputs
    databaseProvider: { type: 'string', required: false },
    databaseCredential: { type: 'string', required: false },
    databaseAirtableCredential: { type: 'string', required: false },
    databaseNotionCredential: { type: 'string', required: false },
    databaseResource: { type: 'string', required: false },
    databaseTriggerType: { type: 'string', required: false },
    databasePollingInterval: { type: 'string', required: false },
    // File inputs
    fileProvider: { type: 'string', required: false },
    fileCredential: { type: 'string', required: false },
    fileOneDriveCredential: { type: 'string', required: false },
    filePath: { type: 'string', required: false },
    fileTriggerType: { type: 'string', required: false },
    fileFilter: { type: 'string', required: false },
    filePollingInterval: { type: 'string', required: false },
    // Calendar inputs
    calendarProvider: { type: 'string', required: false },
    calendarCredential: { type: 'string', required: false },
    calendarOutlookCredential: { type: 'string', required: false },
    calendarId: { type: 'string', required: false },
    calendarTriggerType: { type: 'string', required: false },
    calendarMinutesBefore: { type: 'string', required: false },
    calendarPollingInterval: { type: 'string', required: false },
    // Polling inputs
    pollingUrl: { type: 'string', required: false },
    pollingMethod: { type: 'string', required: false },
    pollingInterval: { type: 'string', required: false },
    pollingHeaders: { type: 'string', required: false },
    pollingBody: { type: 'string', required: false },
    pollingIdentifierPath: { type: 'string', required: false },
  },
  outputs: {
    response: {
      type: {
        input: 'json',
      },
    },
  },
}

/**
 * Trigger-specific output fields for the starter block.
 * Used by connection-panel and tag-dropdown to show available fields
 * based on the selected trigger type (startWorkflow value).
 */
export const TRIGGER_OUTPUT_FIELDS: Record<
  string,
  Array<{ name: string; type: string; description?: string }>
> = {
  // Matches EmailMessage interface in lib/triggers/email-polling.ts
  // Executor flattens first email's fields at response level
  email: [
    { name: 'messageId', type: 'string', description: 'Message ID' },
    { name: 'from', type: 'object', description: 'Sender {name, email}' },
    { name: 'to', type: 'array', description: 'Recipients [{name, email}]' },
    { name: 'cc', type: 'array', description: 'CC recipients' },
    { name: 'subject', type: 'string', description: 'Email subject' },
    { name: 'body', type: 'string', description: 'Plain text body' },
    { name: 'htmlBody', type: 'string', description: 'HTML body' },
    { name: 'date', type: 'string', description: 'Received date' },
    { name: 'attachments', type: 'array', description: 'Attachment list' },
    { name: 'labels', type: 'array', description: 'Email labels' },
    { name: 'folder', type: 'string', description: 'Mail folder' },
    { name: 'provider', type: 'string', description: 'Email provider' },
    { name: 'isRead', type: 'boolean', description: 'Read status' },
    { name: 'hasAttachments', type: 'boolean', description: 'Has attachments' },
    { name: 'emails', type: 'array', description: 'All emails array' },
  ],
  // Webhook input comes from formatWebhookInput in lib/webhooks/utils.ts
  // Structure: { webhook: { data: { path, provider, payload, headers, method } }, workflowId }
  webhook: [
    {
      name: 'webhook',
      type: 'object',
      description: 'Webhook data (payload, headers, method, path, provider)',
    },
    { name: 'workflowId', type: 'string', description: 'Workflow ID' },
  ],
  // Matches FormResponse interface in lib/triggers/form-polling.ts
  // Executor flattens first response's fields at response level
  form: [
    { name: 'responseId', type: 'string', description: 'Form response ID' },
    { name: 'submittedAt', type: 'string', description: 'Submission time' },
    { name: 'answers', type: 'object', description: 'Form answers' },
    { name: 'formId', type: 'string', description: 'Form ID' },
    { name: 'provider', type: 'string', description: 'Form provider' },
    { name: 'responses', type: 'array', description: 'All form responses' },
  ],
  // Matches DatabaseChange interface in lib/triggers/database-polling.ts
  // Executor flattens first change's fields at response level
  database: [
    { name: 'recordId', type: 'string', description: 'Record ID' },
    { name: 'changeType', type: 'string', description: 'insert/update/delete' },
    { name: 'fields', type: 'object', description: 'Record fields' },
    { name: 'createdAt', type: 'string', description: 'Created timestamp' },
    { name: 'provider', type: 'string', description: 'Database provider' },
    { name: 'changes', type: 'array', description: 'All database changes' },
  ],
  // Matches FileChange interface in lib/triggers/file-polling.ts
  // Executor flattens first change's fields at response level
  file: [
    { name: 'fileId', type: 'string', description: 'File ID' },
    { name: 'fileName', type: 'string', description: 'File name' },
    { name: 'mimeType', type: 'string', description: 'MIME type' },
    { name: 'size', type: 'number', description: 'File size' },
    { name: 'modifiedAt', type: 'string', description: 'Modified timestamp' },
    { name: 'changeType', type: 'string', description: 'created/modified/deleted' },
    { name: 'provider', type: 'string', description: 'Storage provider' },
    { name: 'files', type: 'array', description: 'All file changes' },
  ],
  // Matches CalendarEvent interface in lib/triggers/calendar-polling.ts
  // Executor flattens first event's fields at response level
  calendar: [
    { name: 'eventId', type: 'string', description: 'Event ID' },
    { name: 'title', type: 'string', description: 'Event title' },
    { name: 'start', type: 'string', description: 'Start time' },
    { name: 'end', type: 'string', description: 'End time' },
    { name: 'location', type: 'string', description: 'Event location' },
    { name: 'organizer', type: 'string', description: 'Organizer email' },
    { name: 'attendees', type: 'array', description: 'Attendee emails' },
    { name: 'changeType', type: 'string', description: 'created/updated/starting/ended' },
    { name: 'provider', type: 'string', description: 'Calendar provider' },
    { name: 'events', type: 'array', description: 'All calendar events' },
  ],
  schedule: [
    { name: 'scheduledTime', type: 'string', description: 'Scheduled execution time' },
    { name: 'scheduleType', type: 'string', description: 'Schedule type' },
  ],
}
