import { WiseIcon } from '@/components/icons'
import { createOAuthSubBlock, createOperationDropdown, defineBlock } from '../helpers'

export const WiseBlock = defineBlock({
  type: 'wise',
  name: 'Wise',
  description: 'International money transfers and multi-currency accounts.',
  longDescription:
    'Integrate with Wise (formerly TransferWise) to send money internationally, manage multi-currency accounts, and get real-time exchange rates. Wise is a global technology company that makes international money transfers fast, cheap, and transparent. Perfect for businesses and individuals who need to send money across borders with low fees and real exchange rates.',
  category: 'tools',
  bgColor: '#9FE870',
  icon: WiseIcon,
  subBlocks: [
    createOAuthSubBlock({
      provider: 'wise',
      serviceId: 'wise',
      requiredScopes: ['transfers', 'balances', 'profiles'],
      title: 'Wise Account',
      placeholder: 'Select Wise account',
    }),
    createOperationDropdown({
      operations: [
        { id: 'list_profiles', label: 'List Profiles' },
        { id: 'get_profile', label: 'Get Profile' },
        { id: 'list_balances', label: 'List Balances' },
        { id: 'get_balance', label: 'Get Balance' },
        { id: 'create_quote', label: 'Create Quote' },
        { id: 'get_quote', label: 'Get Quote' },
        { id: 'create_transfer', label: 'Create Transfer' },
        { id: 'get_transfer', label: 'Get Transfer' },
        { id: 'list_transfers', label: 'List Transfers' },
        { id: 'fund_transfer', label: 'Fund Transfer' },
        { id: 'get_exchange_rates', label: 'Get Exchange Rates' },
        { id: 'list_recipients', label: 'List Recipients' },
        { id: 'create_recipient', label: 'Create Recipient' },
      ],
      defaultValue: 'list_balances',
    }),
    {
      id: 'profileId',
      title: 'Profile ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter profile ID',
      condition: {
        field: 'operation',
        value: [
          'get_profile',
          'list_balances',
          'create_quote',
          'create_transfer',
          'list_transfers',
          'list_recipients',
          'create_recipient',
        ],
      },
    },
    {
      id: 'balanceId',
      title: 'Balance ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter balance ID',
      condition: { field: 'operation', value: 'get_balance' },
    },
    {
      id: 'quoteId',
      title: 'Quote ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter quote ID',
      condition: { field: 'operation', value: ['get_quote', 'create_transfer'] },
    },
    {
      id: 'transferId',
      title: 'Transfer ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter transfer ID',
      condition: { field: 'operation', value: ['get_transfer', 'fund_transfer'] },
    },
    {
      id: 'sourceCurrency',
      title: 'Source Currency',
      type: 'short-input',
      layout: 'half',
      placeholder: 'USD, EUR, GBP, etc.',
      condition: { field: 'operation', value: ['create_quote', 'get_exchange_rates'] },
    },
    {
      id: 'targetCurrency',
      title: 'Target Currency',
      type: 'short-input',
      layout: 'half',
      placeholder: 'USD, EUR, GBP, etc.',
      condition: { field: 'operation', value: ['create_quote', 'get_exchange_rates'] },
    },
    {
      id: 'sourceAmount',
      title: 'Source Amount',
      type: 'short-input',
      layout: 'half',
      placeholder: '1000.00',
      condition: { field: 'operation', value: 'create_quote' },
    },
    {
      id: 'targetAmount',
      title: 'Target Amount (Optional)',
      type: 'short-input',
      layout: 'half',
      placeholder: '1000.00',
      condition: { field: 'operation', value: 'create_quote' },
    },
    {
      id: 'recipientId',
      title: 'Recipient ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter recipient account ID',
      condition: { field: 'operation', value: 'create_transfer' },
    },
    {
      id: 'recipientName',
      title: 'Recipient Name',
      type: 'short-input',
      layout: 'full',
      placeholder: 'John Doe',
      condition: { field: 'operation', value: 'create_recipient' },
    },
    {
      id: 'recipientEmail',
      title: 'Recipient Email',
      type: 'short-input',
      layout: 'half',
      placeholder: 'john@example.com',
      condition: { field: 'operation', value: 'create_recipient' },
    },
    {
      id: 'recipientCurrency',
      title: 'Recipient Currency',
      type: 'short-input',
      layout: 'half',
      placeholder: 'USD, EUR, GBP',
      condition: { field: 'operation', value: 'create_recipient' },
    },
    {
      id: 'accountDetails',
      title: 'Account Details (JSON)',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder:
        '{"legalType": "PRIVATE", "accountHolderName": "John Doe", "iban": "GB33BUKB20201555555555"}',
      condition: { field: 'operation', value: 'create_recipient' },
    },
    {
      id: 'reference',
      title: 'Transfer Reference',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Payment for invoice #123',
      condition: { field: 'operation', value: 'create_transfer' },
    },
    {
      id: 'transferPurpose',
      title: 'Transfer Purpose',
      type: 'short-input',
      layout: 'full',
      placeholder: 'verification.transfers.purpose.pay.bills',
      condition: { field: 'operation', value: 'create_transfer' },
    },
  ],
  tools: {
    access: ['wise_api'],
    config: {
      tool: () => 'wise_api',
    },
  },
  inputs: {
    credential: { type: 'string', required: true },
    operation: { type: 'string', required: true },
    profileId: { type: 'string', required: false },
    balanceId: { type: 'string', required: false },
    quoteId: { type: 'string', required: false },
    transferId: { type: 'string', required: false },
    sourceCurrency: { type: 'string', required: false },
    targetCurrency: { type: 'string', required: false },
    sourceAmount: { type: 'number', required: false },
    targetAmount: { type: 'number', required: false },
    recipientId: { type: 'string', required: false },
    recipientName: { type: 'string', required: false },
    recipientEmail: { type: 'string', required: false },
    recipientCurrency: { type: 'string', required: false },
    accountDetails: { type: 'json', required: false },
    reference: { type: 'string', required: false },
    transferPurpose: { type: 'string', required: false },
  },
  outputs: {
    response: {
      type: {
        data: 'json',
      },
    },
  },
})
