import { WrikeIcon } from '@/components/icons'
import {
  createOAuthSubBlock,
  createOperationDropdown,
  createSimpleToolConfig,
  defineBlock,
} from '../helpers'

export const WrikeBlock = defineBlock({
  type: 'wrike',
  name: 'Wrike',
  description: 'Project management and collaboration platform for teams.',
  longDescription:
    'Integrate with Wrike to manage projects, tasks, and team collaboration. Wrike is a versatile work management platform that helps teams plan, organize, and collaborate on projects with customizable workflows, Gantt charts, real-time updates, and powerful reporting. Perfect for marketing teams, creative agencies, and project-based organizations.',
  category: 'tools',
  bgColor: '#76BC21',
  icon: WrikeIcon,
  subBlocks: [
    createOAuthSubBlock({
      title: 'Wrike Account',
      provider: 'wrike',
      serviceId: 'wrike',
      requiredScopes: ['Default', 'wsReadWrite'],
    }),
    createOperationDropdown({
      operations: [
        { id: 'list_folders', label: 'List Folders' },
        { id: 'create_folder', label: 'Create Folder' },
        { id: 'list_tasks', label: 'List Tasks' },
        { id: 'get_task', label: 'Get Task' },
        { id: 'create_task', label: 'Create Task' },
        { id: 'update_task', label: 'Update Task' },
        { id: 'list_projects', label: 'List Projects' },
        { id: 'create_project', label: 'Create Project' },
        { id: 'list_comments', label: 'List Comments' },
        { id: 'create_comment', label: 'Create Comment' },
        { id: 'list_timelog', label: 'List Time Logs' },
        { id: 'create_timelog', label: 'Create Time Log' },
      ],
      defaultValue: 'list_tasks',
    }),
    {
      id: 'folderId',
      title: 'Folder ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter folder ID',
      condition: { field: 'operation', value: ['create_task', 'create_project', 'create_folder'] },
    },
    {
      id: 'taskId',
      title: 'Task ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter task ID',
      condition: {
        field: 'operation',
        value: ['get_task', 'update_task', 'list_comments', 'create_comment'],
      },
    },
    {
      id: 'title',
      title: 'Title',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Task or Project title',
      condition: {
        field: 'operation',
        value: ['create_task', 'update_task', 'create_project', 'create_folder'],
      },
    },
    {
      id: 'description',
      title: 'Description',
      type: 'long-input',
      layout: 'full',
      placeholder: 'Detailed description',
      condition: { field: 'operation', value: ['create_task', 'update_task', 'create_project'] },
    },
    {
      id: 'status',
      title: 'Status',
      type: 'short-input',
      layout: 'half',
      placeholder: 'Active, Completed, Deferred, Cancelled',
      condition: { field: 'operation', value: ['create_task', 'update_task'] },
    },
    {
      id: 'importance',
      title: 'Importance',
      type: 'dropdown',
      layout: 'half',
      options: [
        { id: 'High', label: 'High' },
        { id: 'Normal', label: 'Normal' },
        { id: 'Low', label: 'Low' },
      ],
      value: () => 'Normal',
      condition: { field: 'operation', value: ['create_task', 'update_task'] },
    },
    {
      id: 'assignees',
      title: 'Assignee IDs (comma separated)',
      type: 'short-input',
      layout: 'full',
      placeholder: 'USER123,USER456',
      condition: { field: 'operation', value: ['create_task', 'update_task'] },
    },
    {
      id: 'startDate',
      title: 'Start Date',
      type: 'short-input',
      layout: 'half',
      placeholder: '2025-01-01',
      condition: { field: 'operation', value: ['create_task', 'update_task', 'create_project'] },
    },
    {
      id: 'dueDate',
      title: 'Due Date',
      type: 'short-input',
      layout: 'half',
      placeholder: '2025-12-31',
      condition: { field: 'operation', value: ['create_task', 'update_task', 'create_project'] },
    },
    {
      id: 'commentText',
      title: 'Comment Text',
      type: 'long-input',
      layout: 'full',
      placeholder: 'Enter your comment',
      condition: { field: 'operation', value: 'create_comment' },
    },
    {
      id: 'hours',
      title: 'Hours',
      type: 'short-input',
      layout: 'half',
      placeholder: '2.5',
      condition: { field: 'operation', value: 'create_timelog' },
    },
    {
      id: 'trackedDate',
      title: 'Tracked Date',
      type: 'short-input',
      layout: 'half',
      placeholder: '2025-12-27',
      condition: { field: 'operation', value: 'create_timelog' },
    },
    {
      id: 'customFields',
      title: 'Custom Fields (JSON)',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: '{"customField1": "value1"}',
      condition: {
        field: 'operation',
        value: ['create_task', 'update_task', 'create_project'],
      },
    },
  ],
  tools: {
    access: ['wrike_api'],
    config: createSimpleToolConfig('wrike_api'),
  },
  inputs: {
    credential: { type: 'string', required: true },
    operation: { type: 'string', required: true },
    folderId: { type: 'string', required: false },
    taskId: { type: 'string', required: false },
    title: { type: 'string', required: false },
    description: { type: 'string', required: false },
    status: { type: 'string', required: false },
    importance: { type: 'string', required: false },
    assignees: { type: 'string', required: false },
    startDate: { type: 'string', required: false },
    dueDate: { type: 'string', required: false },
    commentText: { type: 'string', required: false },
    hours: { type: 'number', required: false },
    trackedDate: { type: 'string', required: false },
    customFields: { type: 'json', required: false },
  },
  outputs: {
    response: {
      type: {
        data: 'json',
      },
    },
  },
})
