import { ZohoCRMIcon } from '@/components/icons'
import { createOAuthSubBlock, createOperationDropdown, defineBlock } from '../helpers'

export const ZohoCRMBlock = defineBlock({
  type: 'zoho_crm',
  name: 'Zoho CRM',
  description: 'Comprehensive CRM for sales, marketing, and customer support automation.',
  longDescription:
    'Integrate with Zoho CRM to manage contacts, leads, deals, and customer relationships. Zoho CRM provides powerful automation, analytics, and customization options for businesses of all sizes. Access extensive APIs for contact management, deal tracking, and sales pipeline automation with OAuth 2.0 authentication.',
  category: 'tools',
  bgColor: '#E42527',
  icon: ZohoCRMIcon,
  subBlocks: [
    createOAuthSubBlock({
      provider: 'zoho_crm',
      serviceId: 'zoho_crm',
      requiredScopes: ['ZohoCRM.modules.ALL', 'ZohoCRM.settings.ALL'],
      title: 'Zoho CRM Account',
      placeholder: 'Select Zoho CRM account',
    }),
    createOperationDropdown({
      operations: [
        { id: 'list_contacts', label: 'List Contacts' },
        { id: 'get_contact', label: 'Get Contact' },
        { id: 'create_contact', label: 'Create Contact' },
        { id: 'update_contact', label: 'Update Contact' },
        { id: 'list_leads', label: 'List Leads' },
        { id: 'create_lead', label: 'Create Lead' },
        { id: 'list_deals', label: 'List Deals' },
        { id: 'create_deal', label: 'Create Deal' },
        { id: 'get_deal', label: 'Get Deal' },
        { id: 'update_deal', label: 'Update Deal' },
      ],
      defaultValue: 'list_contacts',
    }),
    {
      id: 'contactId',
      title: 'Contact ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter contact ID',
      condition: { field: 'operation', value: ['get_contact', 'update_contact'] },
    },
    {
      id: 'dealId',
      title: 'Deal ID',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Enter deal ID',
      condition: { field: 'operation', value: ['get_deal', 'update_deal'] },
    },
    {
      id: 'firstName',
      title: 'First Name',
      type: 'short-input',
      layout: 'half',
      placeholder: 'John',
      condition: { field: 'operation', value: ['create_contact', 'update_contact', 'create_lead'] },
    },
    {
      id: 'lastName',
      title: 'Last Name',
      type: 'short-input',
      layout: 'half',
      placeholder: 'Doe',
      condition: { field: 'operation', value: ['create_contact', 'update_contact', 'create_lead'] },
    },
    {
      id: 'email',
      title: 'Email',
      type: 'short-input',
      layout: 'half',
      placeholder: 'john@example.com',
      condition: {
        field: 'operation',
        value: ['create_contact', 'update_contact', 'create_lead'],
      },
    },
    {
      id: 'phone',
      title: 'Phone',
      type: 'short-input',
      layout: 'half',
      placeholder: '+1234567890',
      condition: {
        field: 'operation',
        value: ['create_contact', 'update_contact', 'create_lead'],
      },
    },
    {
      id: 'company',
      title: 'Company',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Acme Corp',
      condition: { field: 'operation', value: ['create_contact', 'create_lead'] },
    },
    {
      id: 'dealName',
      title: 'Deal Name',
      type: 'short-input',
      layout: 'full',
      placeholder: 'Q1 Enterprise Deal',
      condition: { field: 'operation', value: ['create_deal', 'update_deal'] },
    },
    {
      id: 'dealStage',
      title: 'Deal Stage',
      type: 'dropdown',
      layout: 'half',
      options: [
        { id: 'Qualification', label: 'Qualification' },
        { id: 'Needs Analysis', label: 'Needs Analysis' },
        { id: 'Value Proposition', label: 'Value Proposition' },
        { id: 'Proposal/Price Quote', label: 'Proposal/Price Quote' },
        { id: 'Negotiation/Review', label: 'Negotiation/Review' },
        { id: 'Closed Won', label: 'Closed Won' },
        { id: 'Closed Lost', label: 'Closed Lost' },
      ],
      condition: { field: 'operation', value: ['create_deal', 'update_deal'] },
    },
    {
      id: 'amount',
      title: 'Amount',
      type: 'short-input',
      layout: 'half',
      placeholder: '50000',
      condition: { field: 'operation', value: ['create_deal', 'update_deal'] },
    },
    {
      id: 'customFields',
      title: 'Custom Fields (JSON)',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: '{"Custom_Field_1": "value1", "Custom_Field_2": "value2"}',
      condition: {
        field: 'operation',
        value: ['create_contact', 'update_contact', 'create_lead', 'create_deal', 'update_deal'],
      },
    },
  ],
  tools: {
    access: ['zoho_crm_api'],
    config: {
      tool: () => 'zoho_crm_api',
    },
  },
  inputs: {
    credential: { type: 'string', required: true },
    operation: { type: 'string', required: true },
    contactId: { type: 'string', required: false },
    dealId: { type: 'string', required: false },
    firstName: { type: 'string', required: false },
    lastName: { type: 'string', required: false },
    email: { type: 'string', required: false },
    phone: { type: 'string', required: false },
    company: { type: 'string', required: false },
    dealName: { type: 'string', required: false },
    dealStage: { type: 'string', required: false },
    amount: { type: 'number', required: false },
    customFields: { type: 'json', required: false },
  },
  outputs: {
    response: {
      type: {
        data: 'json',
      },
    },
  },
})
