import {
  AdobeIcon,
  AirtableIcon,
  BambooHRIcon,
  BasecampIcon,
  BinanceIcon,
  BitbucketIcon,
  CanvaIcon,
  CloseIcon,
  CodaIcon,
  CoinbaseIcon,
  ConfluenceIcon,
  ContentfulIcon,
  ConvertKitIcon,
  CopperIcon,
  FacebookIcon,
  FigmaIcon,
  FreshBooksIcon,
  GithubIcon,
  GmailIcon,
  GoogleCalendarIcon,
  GoogleDocsIcon,
  GoogleDriveIcon,
  GoogleIcon,
  GoogleSheetsIcon,
  GustoIcon,
  InstagramIcon,
  JiraIcon,
  KlaviyoIcon,
  LinkedInIcon,
  LoomIcon,
  MicrosoftIcon,
  MiroIcon,
  NotionIcon,
  OutlookIcon,
  PlanetScaleIcon,
  QuickBooksIcon,
  RobinhoodIcon,
  SanityIcon,
  SAPIcon,
  SegmentIcon,
  SmartsheetIcon,
  StripeIcon,
  SupabaseIcon,
  TeamsIcon,
  VercelIcon,
  WhatsAppIcon,
  WiseIcon,
  WrikeIcon,
  XeroIcon,
  xIcon,
  YouTubeIcon,
  ZohoBooksIcon,
  ZohoCRMIcon,
} from '@/components/icons'
import { OAuthProviderConfig } from './types'

// Define the available OAuth providers
export const OAUTH_PROVIDERS: Record<string, OAuthProviderConfig> = {
  google: {
    id: 'google',
    name: 'Google',
    icon: (props) => GoogleIcon(props),
    services: {
      gmail: {
        id: 'gmail',
        name: 'Gmail',
        description: 'Automate email workflows and enhance communication efficiency.',
        providerId: 'google-email',
        icon: (props) => GmailIcon(props),
        baseProviderIcon: (props) => GoogleIcon(props),
        scopes: [
          'https://www.googleapis.com/auth/gmail.send',
          'https://www.googleapis.com/auth/gmail.readonly',
          'https://www.googleapis.com/auth/gmail.modify',
          'https://www.googleapis.com/auth/gmail.labels',
        ],
      },
      'google-drive': {
        id: 'google-drive',
        name: 'Google Drive',
        description: 'Streamline file organization and document workflows.',
        providerId: 'google-drive',
        icon: (props) => GoogleDriveIcon(props),
        baseProviderIcon: (props) => GoogleIcon(props),
        scopes: ['https://www.googleapis.com/auth/drive.file'],
      },
      'google-docs': {
        id: 'google-docs',
        name: 'Google Docs',
        description: 'Create, read, and edit Google Documents programmatically.',
        providerId: 'google-docs',
        icon: (props) => GoogleDocsIcon(props),
        baseProviderIcon: (props) => GoogleIcon(props),
        scopes: [
          'https://www.googleapis.com/auth/documents',
          'https://www.googleapis.com/auth/drive.file',
        ],
      },
      'google-sheets': {
        id: 'google-sheets',
        name: 'Google Sheets',
        description: 'Manage and analyze data with Google Sheets integration.',
        providerId: 'google-sheets',
        icon: (props) => GoogleSheetsIcon(props),
        baseProviderIcon: (props) => GoogleIcon(props),
        scopes: [
          'https://www.googleapis.com/auth/spreadsheets',
          'https://www.googleapis.com/auth/drive.file',
        ],
      },
      'google-calendar': {
        id: 'google-calendar',
        name: 'Google Calendar',
        description: 'Schedule and manage events with Google Calendar.',
        providerId: 'google-calendar',
        icon: (props) => GoogleCalendarIcon(props),
        baseProviderIcon: (props) => GoogleIcon(props),
        scopes: ['https://www.googleapis.com/auth/calendar'],
      },
      'google-youtube': {
        id: 'google-youtube',
        name: 'YouTube',
        description: 'Read YouTube video, channel, and search metadata.',
        providerId: 'google-youtube',
        icon: (props) => YouTubeIcon(props),
        baseProviderIcon: (props) => GoogleIcon(props),
        scopes: ['https://www.googleapis.com/auth/youtube.readonly'],
      },
      'google-forms': {
        id: 'google-forms',
        name: 'Google Forms',
        description: 'Monitor form responses and automate workflows on new submissions.',
        providerId: 'google-forms',
        icon: (props) => GoogleIcon(props),
        baseProviderIcon: (props) => GoogleIcon(props),
        scopes: [
          'https://www.googleapis.com/auth/forms.responses.readonly',
          'https://www.googleapis.com/auth/forms.body.readonly',
        ],
      },
    },
    defaultService: 'gmail',
  },
  github: {
    id: 'github',
    name: 'GitHub',
    icon: (props) => GithubIcon(props),
    services: {
      github: {
        id: 'github',
        name: 'GitHub',
        description: 'Manage repositories, issues, and pull requests.',
        providerId: 'github-repo',
        icon: (props) => GithubIcon(props),
        baseProviderIcon: (props) => GithubIcon(props),
        scopes: ['repo', 'user:email', 'read:user', 'workflow'],
      },
    },
    defaultService: 'github',
  },
  x: {
    id: 'x',
    name: 'X',
    icon: (props) => xIcon(props),
    services: {
      x: {
        id: 'x',
        name: 'X',
        description: 'Read and post tweets on X (formerly Twitter).',
        providerId: 'x',
        icon: (props) => xIcon(props),
        baseProviderIcon: (props) => xIcon(props),
        scopes: ['tweet.read', 'tweet.write', 'users.read', 'offline.access'],
      },
    },
    defaultService: 'x',
  },
  supabase: {
    id: 'supabase',
    name: 'Supabase',
    icon: (props) => SupabaseIcon(props),
    services: {
      supabase: {
        id: 'supabase',
        name: 'Supabase',
        description: 'Connect to your Supabase projects and manage data.',
        providerId: 'supabase',
        icon: (props) => SupabaseIcon(props),
        baseProviderIcon: (props) => SupabaseIcon(props),
        scopes: ['database.read', 'database.write', 'projects.read'],
      },
    },
    defaultService: 'supabase',
  },
  confluence: {
    id: 'confluence',
    name: 'Confluence',
    icon: (props) => ConfluenceIcon(props),
    services: {
      confluence: {
        id: 'confluence',
        name: 'Confluence',
        description: 'Access Confluence content and documentation.',
        providerId: 'confluence',
        icon: (props) => ConfluenceIcon(props),
        baseProviderIcon: (props) => ConfluenceIcon(props),
        scopes: ['read:page:confluence', 'write:page:confluence', 'read:me', 'offline_access'],
      },
    },
    defaultService: 'confluence',
  },
  jira: {
    id: 'jira',
    name: 'Jira',
    icon: (props) => JiraIcon(props),
    services: {
      jira: {
        id: 'jira',
        name: 'Jira',
        description: 'Access Jira projects and issues.',
        providerId: 'jira',
        icon: (props) => JiraIcon(props),
        baseProviderIcon: (props) => JiraIcon(props),
        scopes: [
          'read:jira-user',
          'read:jira-work',
          'write:jira-work',
          'read:project:jira',
          'read:issue-type:jira',
          'read:me',
          'offline_access',
        ],
      },
    },
    defaultService: 'jira',
  },
  airtable: {
    id: 'airtable',
    name: 'Airtable',
    icon: (props) => AirtableIcon(props),
    services: {
      airtable: {
        id: 'airtable',
        name: 'Airtable',
        description: 'Manage Airtable bases, tables, and records.',
        providerId: 'airtable',
        icon: (props) => AirtableIcon(props),
        baseProviderIcon: (props) => AirtableIcon(props),
        scopes: ['data.records:read', 'data.records:write'],
      },
    },
    defaultService: 'airtable',
  },
  notion: {
    id: 'notion',
    name: 'Notion',
    icon: (props) => NotionIcon(props),
    services: {
      notion: {
        id: 'notion',
        name: 'Notion',
        description: 'Connect to your Notion workspace to manage pages and databases.',
        providerId: 'notion',
        icon: (props) => NotionIcon(props),
        baseProviderIcon: (props) => NotionIcon(props),
        scopes: ['workspace.content', 'workspace.name', 'page.read', 'page.write'],
      },
    },
    defaultService: 'notion',
  },
  microsoft: {
    id: 'microsoft',
    name: 'Microsoft',
    icon: (props) => MicrosoftIcon(props),
    services: {
      'microsoft-teams': {
        id: 'microsoft-teams',
        name: 'Microsoft Teams',
        description:
          'Send messages, create channels, manage team communications, and schedule meetings.',
        providerId: 'microsoft-teams',
        icon: (props) => TeamsIcon(props),
        baseProviderIcon: (props) => MicrosoftIcon(props),
        scopes: [
          'offline_access', // Required for refresh token
          'https://graph.microsoft.com/User.Read',
          'https://graph.microsoft.com/Chat.ReadWrite',
          'https://graph.microsoft.com/Channel.ReadBasic.All',
          'https://graph.microsoft.com/ChannelMessage.Send',
          'https://graph.microsoft.com/Team.ReadBasic.All',
          'https://graph.microsoft.com/TeamMember.Read.All',
          'https://graph.microsoft.com/OnlineMeetings.ReadWrite',
          'https://graph.microsoft.com/Calendars.ReadWrite',
          'https://graph.microsoft.com/Files.ReadWrite.All',
          'https://graph.microsoft.com/Directory.Read.All',
          'https://graph.microsoft.com/TeamsActivity.Read',
          'https://graph.microsoft.com/TeamSettings.ReadWrite.All',
          'https://graph.microsoft.com/TeamsApp.Read.All',
          'https://graph.microsoft.com/Notifications.ReadWrite.CreatedByApp',
        ],
      },
      'microsoft-outlook': {
        id: 'microsoft-outlook',
        name: 'Microsoft Outlook',
        description: 'Send emails, manage calendar events, and access contacts.',
        providerId: 'microsoft-outlook',
        icon: (props) => OutlookIcon(props),
        baseProviderIcon: (props) => MicrosoftIcon(props),
        scopes: [
          'offline_access', // Required for refresh token
          'https://graph.microsoft.com/User.Read',
          'https://graph.microsoft.com/Mail.ReadWrite',
          'https://graph.microsoft.com/Mail.Send',
          'https://graph.microsoft.com/Calendars.ReadWrite',
          'https://graph.microsoft.com/Contacts.ReadWrite',
        ],
      },
      'microsoft-onedrive': {
        id: 'microsoft-onedrive',
        name: 'Microsoft OneDrive',
        description: 'Upload, download, and manage files in OneDrive.',
        providerId: 'microsoft-onedrive',
        icon: (props) => MicrosoftIcon(props),
        baseProviderIcon: (props) => MicrosoftIcon(props),
        scopes: [
          'offline_access', // Required for refresh token
          'https://graph.microsoft.com/User.Read',
          'https://graph.microsoft.com/Files.ReadWrite.All',
          'https://graph.microsoft.com/Sites.ReadWrite.All',
        ],
      },
      'microsoft-sharepoint': {
        id: 'microsoft-sharepoint',
        name: 'Microsoft SharePoint',
        description: 'Access and manage SharePoint sites, lists, and documents.',
        providerId: 'microsoft-sharepoint',
        icon: (props) => MicrosoftIcon(props),
        baseProviderIcon: (props) => MicrosoftIcon(props),
        scopes: [
          'offline_access', // Required for refresh token
          'https://graph.microsoft.com/User.Read',
          'https://graph.microsoft.com/Sites.ReadWrite.All',
          'https://graph.microsoft.com/Files.ReadWrite.All',
        ],
      },
    },
    defaultService: 'microsoft-teams',
  },
  meta: {
    id: 'meta',
    name: 'Meta',
    icon: (props) => FacebookIcon(props),
    services: {
      'meta-facebook': {
        id: 'meta-facebook',
        name: 'Facebook Pages',
        description: 'Manage Facebook Pages, create posts, and access page insights.',
        providerId: 'meta-facebook',
        icon: (props) => FacebookIcon(props),
        baseProviderIcon: (props) => FacebookIcon(props),
        scopes: [
          'pages_manage_posts',
          'pages_read_engagement',
          'pages_show_list',
          'pages_manage_metadata',
          'pages_read_user_content',
          'business_management',
        ],
      },
      'meta-instagram': {
        id: 'meta-instagram',
        name: 'Instagram Business',
        description: 'Publish content to Instagram Business accounts and access insights.',
        providerId: 'meta-instagram',
        icon: (props) => InstagramIcon(props),
        baseProviderIcon: (props) => FacebookIcon(props),
        scopes: [
          'instagram_basic',
          'instagram_content_publish',
          'pages_show_list',
          'pages_read_engagement',
          'business_management',
        ],
      },
      'meta-whatsapp': {
        id: 'meta-whatsapp',
        name: 'WhatsApp Business',
        description: 'Send messages and manage WhatsApp Business accounts.',
        providerId: 'meta-whatsapp',
        icon: (props) => WhatsAppIcon(props),
        baseProviderIcon: (props) => FacebookIcon(props),
        scopes: [
          'whatsapp_business_messaging',
          'whatsapp_business_management',
          'business_management',
        ],
      },
    },
    defaultService: 'meta-facebook',
  },
  linkedin: {
    id: 'linkedin',
    name: 'LinkedIn',
    icon: (props) => LinkedInIcon(props),
    services: {
      linkedin: {
        id: 'linkedin',
        name: 'LinkedIn',
        description: 'Share posts, manage your profile, and connect with your network.',
        providerId: 'linkedin',
        icon: (props) => LinkedInIcon(props),
        baseProviderIcon: (props) => LinkedInIcon(props),
        scopes: ['openid', 'profile', 'email', 'w_member_social'],
      },
    },
    defaultService: 'linkedin',
  },
  sap: {
    id: 'sap',
    name: 'SAP',
    icon: (props) => SAPIcon(props),
    services: {
      s4hana: {
        id: 's4hana',
        name: 'SAP S/4HANA',
        description: 'Access ERP data, manage business processes, and automate workflows.',
        providerId: 'sap-s4hana',
        icon: (props) => SAPIcon(props),
        baseProviderIcon: (props) => SAPIcon(props),
        scopes: [
          'API_SALES_ORDER_SRV_0001',
          'API_BUSINESS_PARTNER',
          'API_MATERIAL_STOCK_SRV',
          'API_PRODUCTION_ORDER_2_SRV',
        ],
      },
      successfactors: {
        id: 'successfactors',
        name: 'SAP SuccessFactors',
        description: 'Manage HR processes, employee data, and workforce analytics.',
        providerId: 'sap-successfactors',
        icon: (props) => SAPIcon(props),
        baseProviderIcon: (props) => SAPIcon(props),
        scopes: [
          'user_management',
          'employee_central',
          'recruiting',
          'performance_goals',
          'learning',
        ],
      },
      concur: {
        id: 'concur',
        name: 'SAP Concur',
        description: 'Automate expense reporting, travel booking, and invoice management.',
        providerId: 'sap-concur',
        icon: (props) => SAPIcon(props),
        baseProviderIcon: (props) => SAPIcon(props),
        scopes: [
          'expense.report.read',
          'expense.report.write',
          'travel.request.read',
          'travel.request.write',
          'invoice.read',
          'invoice.write',
        ],
      },
      ariba: {
        id: 'ariba',
        name: 'SAP Ariba',
        description: 'Manage procurement, supplier relationships, and sourcing processes.',
        providerId: 'sap-ariba',
        icon: (props) => SAPIcon(props),
        baseProviderIcon: (props) => SAPIcon(props),
        scopes: [
          'procurement.read',
          'procurement.write',
          'supplier.read',
          'supplier.write',
          'sourcing.read',
          'contract.read',
        ],
      },
      fieldglass: {
        id: 'fieldglass',
        name: 'SAP Fieldglass',
        description: 'Manage contingent workforce, vendor management, and services procurement.',
        providerId: 'sap-fieldglass',
        icon: (props) => SAPIcon(props),
        baseProviderIcon: (props) => SAPIcon(props),
        scopes: [
          'worker.read',
          'worker.write',
          'job_posting.read',
          'job_posting.write',
          'timesheet.read',
          'invoice.read',
        ],
      },
      'business-one': {
        id: 'business-one',
        name: 'SAP Business One',
        description: 'Manage SMB operations including financials, sales, and inventory.',
        providerId: 'sap-business-one',
        icon: (props) => SAPIcon(props),
        baseProviderIcon: (props) => SAPIcon(props),
        scopes: [
          'sl.businesspartner',
          'sl.items',
          'sl.orders',
          'sl.invoices',
          'sl.inventory',
          'sl.generalledger',
        ],
      },
    },
    defaultService: 's4hana',
  },
  figma: {
    id: 'figma',
    name: 'Figma',
    icon: FigmaIcon,
    services: {
      figma: {
        id: 'figma',
        name: 'Figma',
        description: 'Access design files, components, and collaborate on designs.',
        providerId: 'figma',
        icon: FigmaIcon,
        baseProviderIcon: FigmaIcon,
        scopes: [
          'file_content:read',
          'file_metadata:read',
          'file_comments:write',
          'file_comments:read',
        ],
      },
    },
    defaultService: 'figma',
  },
  canva: {
    id: 'canva',
    name: 'Canva',
    icon: CanvaIcon,
    services: {
      canva: {
        id: 'canva',
        name: 'Canva',
        description: 'Create designs, manage assets, and automate design workflows.',
        providerId: 'canva',
        icon: CanvaIcon,
        baseProviderIcon: CanvaIcon,
        scopes: [
          'design:content:read',
          'design:content:write',
          'design:meta:read',
          'asset:read',
          'asset:write',
          'folder:read',
          'folder:write',
        ],
      },
    },
    defaultService: 'canva',
  },
  bitbucket: {
    id: 'bitbucket',
    name: 'Bitbucket',
    icon: BitbucketIcon,
    services: {
      bitbucket: {
        id: 'bitbucket',
        name: 'Bitbucket',
        description: 'Manage repositories, pull requests, and automate development workflow.',
        providerId: 'bitbucket',
        icon: BitbucketIcon,
        baseProviderIcon: BitbucketIcon,
        scopes: ['account', 'repository', 'repository:write', 'pullrequest', 'pullrequest:write'],
      },
    },
    defaultService: 'bitbucket',
  },
  adobe: {
    id: 'adobe',
    name: 'Adobe',
    icon: AdobeIcon,
    services: {
      'adobe-cc': {
        id: 'adobe-cc',
        name: 'Adobe Creative Cloud',
        description: 'Access Creative Cloud libraries and assets from Adobe apps.',
        providerId: 'adobe-cc',
        icon: AdobeIcon,
        baseProviderIcon: AdobeIcon,
        scopes: ['openid', 'creative_sdk', 'AdobeID', 'profile', 'email'],
      },
    },
    defaultService: 'adobe-cc',
  },
  quickbooks: {
    id: 'quickbooks',
    name: 'QuickBooks',
    icon: QuickBooksIcon,
    services: {
      quickbooks: {
        id: 'quickbooks',
        name: 'QuickBooks',
        description: 'Manage accounting and financial data with QuickBooks.',
        providerId: 'quickbooks',
        icon: QuickBooksIcon,
        baseProviderIcon: QuickBooksIcon,
        scopes: ['com.intuit.quickbooks.accounting'],
      },
    },
    defaultService: 'quickbooks',
  },
  xero: {
    id: 'xero',
    name: 'Xero',
    icon: XeroIcon,
    services: {
      xero: {
        id: 'xero',
        name: 'Xero',
        description: 'Manage accounting and bookkeeping with Xero.',
        providerId: 'xero',
        icon: XeroIcon,
        baseProviderIcon: XeroIcon,
        scopes: [
          'openid',
          'profile',
          'email',
          'accounting.transactions',
          'accounting.contacts',
          'accounting.settings',
          'offline_access',
        ],
      },
    },
    defaultService: 'xero',
  },
  freshbooks: {
    id: 'freshbooks',
    name: 'FreshBooks',
    icon: FreshBooksIcon,
    services: {
      freshbooks: {
        id: 'freshbooks',
        name: 'FreshBooks',
        description: 'Manage invoicing, time tracking, and expenses.',
        providerId: 'freshbooks',
        icon: FreshBooksIcon,
        baseProviderIcon: FreshBooksIcon,
        scopes: [
          'user:profile:read',
          'user:clients:read',
          'user:clients:write',
          'user:time_entries:read',
          'user:time_entries:write',
          'user:expenses:read',
          'user:expenses:write',
          'user:invoices:read',
          'user:invoices:write',
        ],
      },
    },
    defaultService: 'freshbooks',
  },
  zoho_books: {
    id: 'zoho_books',
    name: 'Zoho Books',
    icon: ZohoBooksIcon,
    services: {
      zoho_books: {
        id: 'zoho_books',
        name: 'Zoho Books',
        description: 'Comprehensive accounting within Zoho ecosystem.',
        providerId: 'zoho_books',
        icon: ZohoBooksIcon,
        baseProviderIcon: ZohoBooksIcon,
        scopes: ['ZohoBooks.fullaccess.all'],
      },
    },
    defaultService: 'zoho_books',
  },
  miro: {
    id: 'miro',
    name: 'Miro',
    icon: MiroIcon,
    services: {
      miro: {
        id: 'miro',
        name: 'Miro',
        description: 'Create and manage visual collaboration boards.',
        providerId: 'miro',
        icon: MiroIcon,
        baseProviderIcon: MiroIcon,
        scopes: ['boards:read', 'boards:write'],
      },
    },
    defaultService: 'miro',
  },
  loom: {
    id: 'loom',
    name: 'Loom',
    icon: LoomIcon,
    services: {
      loom: {
        id: 'loom',
        name: 'Loom',
        description: 'Record and share video messages.',
        providerId: 'loom',
        icon: LoomIcon,
        baseProviderIcon: LoomIcon,
        scopes: ['video:read', 'video:write'],
      },
    },
    defaultService: 'loom',
  },
  basecamp: {
    id: 'basecamp',
    name: 'Basecamp',
    icon: BasecampIcon,
    services: {
      basecamp: {
        id: 'basecamp',
        name: 'Basecamp',
        description: 'Project management and team communication.',
        providerId: 'basecamp',
        icon: BasecampIcon,
        baseProviderIcon: BasecampIcon,
        scopes: [],
      },
    },
    defaultService: 'basecamp',
  },
  smartsheet: {
    id: 'smartsheet',
    name: 'Smartsheet',
    icon: SmartsheetIcon,
    services: {
      smartsheet: {
        id: 'smartsheet',
        name: 'Smartsheet',
        description: 'Spreadsheet-style project management.',
        providerId: 'smartsheet',
        icon: SmartsheetIcon,
        baseProviderIcon: SmartsheetIcon,
        scopes: ['READ_SHEETS', 'WRITE_SHEETS', 'READ_USERS', 'DELETE_SHEETS', 'SHARE_SHEETS'],
      },
    },
    defaultService: 'smartsheet',
  },
  coda: {
    id: 'coda',
    name: 'Coda',
    icon: CodaIcon,
    services: {
      coda: {
        id: 'coda',
        name: 'Coda',
        description: 'All-in-one doc platform.',
        providerId: 'coda',
        icon: CodaIcon,
        baseProviderIcon: CodaIcon,
        scopes: ['readonly', 'write', 'admin'],
      },
    },
    defaultService: 'coda',
  },
  klaviyo: {
    id: 'klaviyo',
    name: 'Klaviyo',
    icon: KlaviyoIcon,
    services: {
      klaviyo: {
        id: 'klaviyo',
        name: 'Klaviyo',
        description: 'Ecommerce email and SMS marketing.',
        providerId: 'klaviyo',
        icon: KlaviyoIcon,
        baseProviderIcon: KlaviyoIcon,
        scopes: [
          'profiles:read',
          'profiles:write',
          'campaigns:read',
          'campaigns:write',
          'metrics:read',
        ],
      },
    },
    defaultService: 'klaviyo',
  },
  convertkit: {
    id: 'convertkit',
    name: 'ConvertKit',
    icon: ConvertKitIcon,
    services: {
      convertkit: {
        id: 'convertkit',
        name: 'ConvertKit',
        description: 'Email marketing platform for creators.',
        providerId: 'convertkit',
        icon: ConvertKitIcon,
        baseProviderIcon: ConvertKitIcon,
        scopes: [],
      },
    },
    defaultService: 'convertkit',
  },
  contentful: {
    id: 'contentful',
    name: 'Contentful',
    icon: ContentfulIcon,
    services: {
      contentful: {
        id: 'contentful',
        name: 'Contentful',
        description: 'Enterprise headless CMS.',
        providerId: 'contentful',
        icon: ContentfulIcon,
        baseProviderIcon: ContentfulIcon,
        scopes: ['content_management_manage'],
      },
    },
    defaultService: 'contentful',
  },
  sanity: {
    id: 'sanity',
    name: 'Sanity',
    icon: SanityIcon,
    services: {
      sanity: {
        id: 'sanity',
        name: 'Sanity',
        description: 'Real-time headless CMS with GROQ.',
        providerId: 'sanity',
        icon: SanityIcon,
        baseProviderIcon: SanityIcon,
        scopes: [],
      },
    },
    defaultService: 'sanity',
  },
  vercel: {
    id: 'vercel',
    name: 'Vercel',
    icon: VercelIcon,
    services: {
      vercel: {
        id: 'vercel',
        name: 'Vercel',
        description: 'Frontend deployment platform.',
        providerId: 'vercel',
        icon: VercelIcon,
        baseProviderIcon: VercelIcon,
        scopes: [],
      },
    },
    defaultService: 'vercel',
  },
  planetscale: {
    id: 'planetscale',
    name: 'PlanetScale',
    icon: PlanetScaleIcon,
    services: {
      planetscale: {
        id: 'planetscale',
        name: 'PlanetScale',
        description: 'Serverless MySQL with branching.',
        providerId: 'planetscale',
        icon: PlanetScaleIcon,
        baseProviderIcon: PlanetScaleIcon,
        scopes: [],
      },
    },
    defaultService: 'planetscale',
  },
  segment: {
    id: 'segment',
    name: 'Segment',
    icon: SegmentIcon,
    services: {
      segment: {
        id: 'segment',
        name: 'Segment',
        description: 'Customer data platform for collecting and routing data.',
        providerId: 'segment',
        icon: SegmentIcon,
        baseProviderIcon: SegmentIcon,
        scopes: [],
      },
    },
    defaultService: 'segment',
  },
  zoho_crm: {
    id: 'zoho_crm',
    name: 'Zoho CRM',
    icon: ZohoCRMIcon,
    services: {
      zoho_crm: {
        id: 'zoho_crm',
        name: 'Zoho CRM',
        description: 'Comprehensive CRM for sales, marketing, and customer support.',
        providerId: 'zoho_crm',
        icon: ZohoCRMIcon,
        baseProviderIcon: ZohoCRMIcon,
        scopes: ['ZohoCRM.modules.ALL', 'ZohoCRM.settings.ALL'],
      },
    },
    defaultService: 'zoho_crm',
  },
  copper: {
    id: 'copper',
    name: 'Copper',
    icon: CopperIcon,
    services: {
      copper: {
        id: 'copper',
        name: 'Copper',
        description: 'Google Workspace native CRM for managing relationships.',
        providerId: 'copper',
        icon: CopperIcon,
        baseProviderIcon: CopperIcon,
        scopes: [],
      },
    },
    defaultService: 'copper',
  },
  close: {
    id: 'close',
    name: 'Close',
    icon: CloseIcon,
    services: {
      close: {
        id: 'close',
        name: 'Close',
        description: 'Sales CRM built for startups and SMBs.',
        providerId: 'close',
        icon: CloseIcon,
        baseProviderIcon: CloseIcon,
        scopes: [],
      },
    },
    defaultService: 'close',
  },
  wrike: {
    id: 'wrike',
    name: 'Wrike',
    icon: WrikeIcon,
    services: {
      wrike: {
        id: 'wrike',
        name: 'Wrike',
        description: 'Project management and collaboration platform.',
        providerId: 'wrike',
        icon: WrikeIcon,
        baseProviderIcon: WrikeIcon,
        scopes: ['Default', 'wsReadWrite'],
      },
    },
    defaultService: 'wrike',
  },
  gusto: {
    id: 'gusto',
    name: 'Gusto',
    icon: GustoIcon,
    services: {
      gusto: {
        id: 'gusto',
        name: 'Gusto',
        description: 'Modern payroll, benefits, and HR platform.',
        providerId: 'gusto',
        icon: GustoIcon,
        baseProviderIcon: GustoIcon,
        scopes: [],
      },
    },
    defaultService: 'gusto',
  },
  bamboohr: {
    id: 'bamboohr',
    name: 'BambooHR',
    icon: BambooHRIcon,
    services: {
      bamboohr: {
        id: 'bamboohr',
        name: 'BambooHR',
        description: 'HR software for small and medium-sized businesses.',
        providerId: 'bamboohr',
        icon: BambooHRIcon,
        baseProviderIcon: BambooHRIcon,
        scopes: [],
      },
    },
    defaultService: 'bamboohr',
  },
  wise: {
    id: 'wise',
    name: 'Wise',
    icon: WiseIcon,
    services: {
      wise: {
        id: 'wise',
        name: 'Wise',
        description: 'International money transfers and multi-currency accounts.',
        providerId: 'wise',
        icon: WiseIcon,
        baseProviderIcon: WiseIcon,
        scopes: ['transfers', 'balances', 'profiles'],
      },
    },
    defaultService: 'wise',
  },
  stripe: {
    id: 'stripe',
    name: 'Stripe',
    icon: StripeIcon,
    services: {
      stripe: {
        id: 'stripe',
        name: 'Stripe Connect',
        description:
          'Payment processing, connected accounts, and platform management with Stripe Connect OAuth 2.0.',
        providerId: 'stripe',
        icon: StripeIcon,
        baseProviderIcon: StripeIcon,
        scopes: ['read_write'], // read_only or read_write - controls access to connected accounts
      },
    },
    defaultService: 'stripe',
  },
  binance: {
    id: 'binance',
    name: 'Binance',
    icon: (props) => BinanceIcon(props),
    services: {
      binance: {
        id: 'binance',
        name: 'Binance',
        description:
          '⚠️ Cryptocurrency trading, market data, and wallet management. EXTREME RISK: Crypto trading carries high financial risk.',
        providerId: 'binance',
        icon: (props) => BinanceIcon(props),
        baseProviderIcon: (props) => BinanceIcon(props),
        scopes: ['spot', 'wallet'], // Spot trading and wallet access
      },
    },
    defaultService: 'binance',
  },
  coinbase: {
    id: 'coinbase',
    name: 'Coinbase',
    icon: (props) => CoinbaseIcon(props),
    services: {
      coinbase: {
        id: 'coinbase',
        name: 'Coinbase',
        description:
          '⚠️ Cryptocurrency wallet, trading, and payment integration. HIGH RISK: Crypto transactions carry financial risk.',
        providerId: 'coinbase',
        icon: (props) => CoinbaseIcon(props),
        baseProviderIcon: (props) => CoinbaseIcon(props),
        scopes: [
          'wallet:accounts:read',
          'wallet:transactions:read',
          'wallet:buys:read',
          'wallet:sells:read',
        ],
      },
    },
    defaultService: 'coinbase',
  },
  robinhood: {
    id: 'robinhood',
    name: 'Robinhood',
    icon: (props) => RobinhoodIcon(props),
    services: {
      robinhood: {
        id: 'robinhood',
        name: 'Robinhood',
        description:
          '⚠️ Commission-free stock and crypto trading. HIGH RISK: Investment carries risk of financial loss. US-only service.',
        providerId: 'robinhood',
        icon: (props) => RobinhoodIcon(props),
        baseProviderIcon: (props) => RobinhoodIcon(props),
        scopes: ['account:read', 'trading', 'portfolio:read'],
      },
    },
    defaultService: 'robinhood',
  },
}
