export {
  ModernFilterIcon,
  ModernSearchIcon,
  ModernRefreshIcon,
  ModernLiveIcon,
  ModernStopIcon,
  ModernInfoIcon,
  ModernAlertIcon,
  ModernLoaderIcon,
  ModernClockIcon,
  ModernStatusIcon,
  ModernWorkflowIcon,
  ModernIdIcon,
  ModernTriggerIcon,
  ModernMessageIcon,
  ModernDurationIcon,
  ModernErrorIcon,
  ModernSuccessIcon,
  ModernLogsIcon,
  ModernUploadIcon,
} from '@/components/modern-icons/registry'
