// Barrel file - re-exports all schema tables from domain files
// All imports like `import { users, workflows } from '@/db/schema'` continue to work

export * from './users'
export * from './auth'
export * from './organizations'
export * from './workspaces'
export * from './workflows'
export * from './billing'
export * from './knowledge'
export * from './files'
export * from './agents'
export * from './chat'
export * from './webhooks'
export * from './marketplace'
export * from './blog'
export * from './audiences'
export * from './data-tables'
export * from './hitl'
export * from './debug'
export * from './analytics'
export * from './gateway'
export * from './misc'
export * from './community'
